### ISSUE TITLE
Disponibilizar as movimentações da APyB para a comunidade

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#1]
## Descrição

Pensando no máximo de transparência possível, gostaria muito que disponibilizássemos os extratos mensais da conta da APyB de forma pública, e se possível automática também 😅. A princípio, pensei em um conjunto de JSONs ou CSVs para que a comunidade em geral pudesse utilizar esses dados da forma que melhor entender.

## Requisitos para a atividade ser considerada concluída

Definir o escopo da solução que disponibilizará a movimentação da conta da APyB à comunidade.

## Ideias

Pensei em um script de OCR para extrair as movimentações através do extrato mensal da conta da APyB. Logicamente, os dados extraídos precisariam de uma, ou mais, revisões manuais para garantir que o output do script está correto. Essa abordagem gera um trabalho mensal para a diretoria, apesar de simples, ainda assim é uma alocação de tempo que precisa ser disposta.

Outras ideias são super bem-vindas!

**Comment by muriloviana** [comment]
Após ter acesso a conta bancária da associação, descobrimos que é possível exportar os extratos mensais em CSV. Logo, isso facilita bastante nosso trabalho.

Agora precisamos decidir qual a melhor forma de tornar esses arquivos CSV públicos para a comunidade.

**Comment by gabubellon** [comment]
@muriloviana acho que pode ser feito algo parecido com o https://ok.org.br/transparencia-de-contas/
Uma ideia sería deixar esses csv anoniomizados onde necessário, e deixar eles publicos no git, podemos fazer um site para exibir as informaçoes desse csv
Pode ser feito um envio mensal de um email/newsletter detalhando alguma coisas e linkando para esse painel online

(Estou disposto em ajudar em todas as sugestões acima :D)

**Comment by muriloviana** [comment]
Gosto da sua ideia @gabubellon!

Só pra organizar rs, nesse primeiro momento a gente foca apenas em disponibilizar esses arquivos anonimizados de forma pública. E em uma segunda issue, que inclusive já pode ficar aberta rs, criarmos uma visualização mais amigável desses dados. O que acha?

**Comment by gabubellon** [comment]
Eu acho lindo!

**Comment by cuducos** [comment]
> podemos fazer um site para exibir as informaçoes desse csv

Como o site de associados é um Django, rola utilizar o [`django-public-admin`](https://django-public-admin.readthedocs.io/) — criamos um modelo no Django com as colunas do CSV, importamos e tudo fica organizadinho num _Django Admin_ público (não requer login, nem permite edição/criação/exclusão de dados) — é o que a Serenata usa no [Jarbas](https://jarbas.serenata.ai) e o Dados Abertos de Feira usa no [Maria Quitéria](https://mq.dadosabertosdefeira.com.br/painel/).

Aviso: esse comentário tem um viés enorme já que sou o criador do `django-public-admin` — mas pelo menos me disponho a implementar isso (bem como o modelo e o script de importação) hahaha…

**Comment by muriloviana** [comment]
No nosso repositório de discussão, foi levantado o ponto de que seria necessário uma consultoria jurídica para nos auxiliar a decidir quais dados anonimizar e de qual forma isso deveria ser feito. (https://github.com/apyb/comunidade/discussions/14).

Analisamos os orçamentos dos profissionais, sugeridos pela própria comunidade, e escolhemos o Bruno Morassutti para nos auxiliar nesta tarefa de anonimização. Portante, nesta quarta-feira (13/04/2022) daremos início ao processo de disponibilizar, de forma pública, as movimentações bancárias da associação.

**Comment by muriloviana** [comment]
Checklist para considerarmos esta tarefa finalizada:

- [ ] #52
- [ ] #53
- [ ] #54
- [ ] #55

**Comment by rougeth** [comment]
@muriloviana concluímos essa issue, né?

**Comment by muriloviana** [comment]
Finalizado: https://financeiro.python.org.br
