### ISSUE TITLE
Reunião Diretoria - 25 de Julho, 2022

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#109]
# Reunião Diretoria - 25/07/2022

## Sobre
- **Assunto**: Alinhamento quinzenal
- **Participantes**:
  - Ana Dulce Padovan @anadulce  
  - Juliana Barros Lima @tiidadavena
  - Marco Rougeth @rougeth 
  - Murilo Viana @muriloviana 

## Pautas
- Python Sul
- Demandas jurídicas
- Palestra na Python Brasil
- Email flask@python.org.br
- Status PyNE e PyBR
- Boletim #105
- 6 meses de mandato 🎉

### Python Sul

- #123
    - Reembolso através do Eventbrite, num vai rolar
    - Abordagem preferível: entrar em contato pelo próprio Eventbrite com as pessoas que compraram ingressos, perguntando se aceitas pix. A pessoa precisaria passar os dados para receber o reembolso.
    - Abordagem caso a primeira não dê certo: solicitar a confirmação de compra do ingresso enviado pelo Eventbrite, através do email de compra, juntamente com os dados para reembolso.

### Demandas jurídicas

- #122 
    - Criar e enviar um email para o Bruno, advogado que fez os termos de consentimento da transperência de movimentações financeiras da associação, solicitando dois orçamentos:
        1. Gerar um modelo de contrato de patrocícnio (dúvida: prestação de serviço entra aqui?) a ser utilizado nos eventos.
        2. Valor para revisar determinados contratos independentes ou com alterações solicitadas pela empresa terceira.

### Palestra na Python Brasil

**Issue:**  #120

- #124
    - A palestra da APyB não pode conflitar com a assembleia. Ideia de realizá-la no primeiro dia de palestras.
    - Preferencialmente no domingo das 10h30 às 12h30.

### Acesso ao email flask@python.org.br

**Issue:** https://github.com/apyb/comunidade/discussions/33

- Adicionar e-mail da Bianca para receber emails de flask@python.org.br;
- Perguntar se acesso ao grupo é o suficiente;

### Status PyNE e PyBR

- Tudo de boa na lagoa.
- Patrocínios sendo firmados 
- Poucos pagamentos

### Boletim

**Issue:** #105
- #55
- #52

### 6 meses de mandato 🎉

<3

**Comment by rougeth** [comment]
Status da Python Sul.

**Comment by rougeth** [comment]
6 meses de mandato 🎉

**Comment by rougeth** [comment]
Demandas para o Bruno.

**Comment by rougeth** [comment]
https://docs.google.com/document/d/e/2PACX-1vSR7b34tVB5RqT0n4BwSx2riYraL2c88eK4ylyC38t_QeauryRghobt6hVg8Ql-pZn-GdFKcfsunVfI/pub

**Comment by rougeth** [comment]
Palestra na pybr.

**Comment by muriloviana** [comment]
> Status da Python Sul.

Ainda sobre a Python Sul, o Francisco Alface questionou sobre os reembolsos dos participantes que compraram ingressos para o evento de 2020. Como o dinheiro foi debitado da conta do Eventbrite, precisamos ver como isso será feito.
