### ISSUE TITLE
Organizar Assembleia Geral 2022

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#11]
## Descrição

Criando tarefa para organizarmos a assembleia geral de 2022.

- [x] https://github.com/pythonbrasil/pybr2022-org/issues/53
- [ ] Convidar associados para assembleia geral, **com antecedência mínima de 30 dias**.

**Comment by rougeth** [comment]
Marcando como bloqueada, já que precisamos fechar o dia, horário e local da assembleia com a organização da pybr2022.

**Comment by tiidadavena** [comment]
Tópicos para a Assembleia Geral: https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/BksbWt-ki/edit

**Comment by tiidadavena** [comment]
Falta confirmar com a org:
- Sala da palestra
- Duração

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/188516706-cc4d1933-8253-40b9-8668-423ee16b5363.png)
uma das salas seria a dedicada para as palestras

**Comment by tiidadavena** [comment]
![Assembleia Geral 2022](https://user-images.githubusercontent.com/12106738/190515433-bc9e2213-64c3-4d60-9388-ceec01864900.png)

**Comment by tiidadavena** [comment]
https://python.org.br/assembleia2022

**Comment by tiidadavena** [comment]
Falta definir: auditório
