### ISSUE TITLE
Pagar impostos relativos ao mês de junho

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#113]

**Comment by rougeth** [comment]
@muriloviana como vc sabe quais são os impostos que precisam ser pagos?

**Comment by muriloviana** [comment]
A contadora da associação, Maria do Carmo, mandou pra gente os impostos com base nas notas que emitimos no mês anterior

**Comment by muriloviana** [comment]
Guia de ISSQN paga: https://drive.google.com/file/d/17iOjcpA6mdf0MnNW6_GwRSMiU0GssTt2/view?usp=sharing

**Comment by rennerocha** [comment]
É possível tornar público (talvez anexar a guia do ISSQN paga aqui na issue?
Eu não sei o quanto de imposto foi pago.

**Comment by muriloviana** [comment]
> É possível tornar público (talvez anexar a guia do ISSQN paga aqui na issue?
> Eu não sei o quanto de imposto foi pago.

Liberado. por padrão o Driver cria com acesso restrito. Vou verificar a possibilidade de sempre ficar disponível via link.
