### ISSUE TITLE
Reembolsos Python Sul 2020

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#123]
Discutido na reunião do dia 25 de Julho, 2022:

- Reembolso através do Eventbrite, num vai rolar
- Abordagem preferível: entrar em contato pelo próprio Eventbrite com as pessoas que compraram ingressos, perguntando se aceitas pix. A pessoa precisaria passar os dados para receber o reembolso.
- Abordagem caso a primeira não dê certo: solicitar a confirmação de compra do ingresso enviado pelo Eventbrite, através do email de compra, juntamente com os dados para reembolso.

**Comment by muriloviana** [comment]
A organização da Python Sul já entrou em contato com todas as pessoas que compraram ingressos. Portanto, sugeri de criarmos uma planilha onde eles irão adicionar as solicitações com os dados bancários e nós fazemos os reembolsos.

Seria interessante, se possível, cancelar o ingressos das pessoas reembolsadas lá no Eventbrite.

**Comment by alynnefs** [comment]
Considerando que recebi meu reembolso, as outras pessoas também devem ter recebido. Não é o caso de fechar a issue?
