### ISSUE TITLE
Palestra APyB na Python Brasil 2022

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#124]
Discutido na reunião de 25 de Julho, 2022:

- A palestra da APyB não pode conflitar com a assembleia. Ideia de realizá-la no primeiro dia de palestras.
- Preferencialmente no domingo das 10h30 às 12h30.

**Comment by tiidadavena** [comment]
- Apresentar o que é a APyB
- Revisar os dados do Boletim Informativo
- Eventos que foram apoiados
- Ajustar template

**Comment by tiidadavena** [comment]
Slides das palestras feitas na Assembleia:

[https://docs.google.com/presentation/d/1S7ClEEScfA9Zzf2GAwwzrUT0BOHOWxyTcIHG4yVAvd8/edit?usp=sharing](https://docs.google.com/presentation/d/1S7ClEEScfA9Zzf2GAwwzrUT0BOHOWxyTcIHG4yVAvd8/edit?usp=sharing&authuser=1)
[https://docs.google.com/presentation/d/1_uTXq3nhFHhZZLn70JPRJ7AIAJMsNlXEGfGI7bz_qNc/edit?usp=sharing](https://docs.google.com/presentation/d/1_uTXq3nhFHhZZLn70JPRJ7AIAJMsNlXEGfGI7bz_qNc/edit?usp=sharing&authuser=1)

**Comment by rougeth** [comment]
Copiei/colei os seus tópicos @tiidadavena e adicionei algumas coisas tbm: https://hackmd.io/2u-A7kOFTVehAv3VtpciuQ
Criei esse hackmd pra ficar mais fácil editarmos as ideias.

**Comment by tiidadavena** [comment]
Foram adicionados mais alguns tópicos no roteiro

**Comment by tiidadavena** [comment]
Falta confirmar com a org:
- Sala da palestra
- Duração

**Comment by tiidadavena** [comment]
Reservar data para o dia 20/10

**Comment by tiidadavena** [comment]
Template Inicializado no Canva: https://www.canva.com/design/DAFLfsqNosE/evEvXBcZQiPVB5qg8YI2Uw/edit?utm_content=DAFLfsqNosE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

O material base são os slides dos Relatórios Apresentados nos últimos anos.

**Comment by tiidadavena** [comment]
https://www.flickr.com/photos/pythonbrasil/albums

**Comment by tiidadavena** [comment]
### Feedbacks
> 30min de conteúdo + 15min de perguntas e respostas

- mais fotos dps da seção de eventos
- outros canais válidos de comunicação com a comunidade
- como você pode comunicar-se com a APyB?
- o que a gente quer que as pessoas entendam/sintam?
- o que queremos apresentar para os espectadores?
- explicitar que as ações SÃO pela comunidade, e a APyB só apoia
- Demonstrar como a APyB pode ajudar nas iniciativas lideradas pela comunidade
- pessoas > comunidade <fotos dos eventos>

**Comment by tiidadavena** [comment]
Palestra realizada no dia 20/10 no primeiro dia de palestras da Python Brasil 2022 sediada em Manaus - AM
