### ISSUE TITLE
 Acesso ao email flask@python.org.br

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#133]
Fechando a discussão aqui https://github.com/apyb/comunidade/discussions/33 em favor da issue pq o repositorio faz mais sentido :)

Galera, qual é processo pra conseguir acesso a esse email? :)

Abçs.

**Comment by rougeth** [comment]
@biancarosa tava vendo na nossa conta, esse @ é na verdade uma lista de email. Posso adicionar o seu email para receber o que chega por lá, funciona para vocês?

**Comment by biancarosa** [comment]
perfeito! consegue adicionar me@biancarosa.com.br? :)

**Comment by rougeth** [comment]
Adicionei @biancarosa, pinga a gente se precisar adicionar mais gente.
