### ISSUE TITLE
Reunião Diretoria - 22 de Agosto, 2022

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#149]
# Reunião Diretoria - 22 de Agosto, 2022

## Sobre
- **Assunto**: Alinhamento quinzenal
- **Participantes**:
  - Juliana Barros Lima @tiidadavena
  - Marco Rougeth @rougeth
  - Murilo Viana @muriloviana

## Pautas
- Organizar Assembleia Geral 2022 #11
- Publicação do Fundo de Inclusão #151
- Palestra APyB na Python Brasil 2022 #124
- Traduzir termo de consentimento PJ para Inglês #158
- Atualizar documentação de como emitir Nota Fiscal #159
- Prêmio Dornéles Jean #103
- Boletim Informativo - Agosto, 2022 #150
- TW requisitou boleto para pagar o patrocínio da PyBR
- Solicitar orçamento com Bruno sobre o modelo de contrato de patrocínio
- Incluir exemplo de transação parcialmente ofuscada no termo de consentimento PF #37 

### Tópico

**Issue:** #<número-da-issue>
<Discussão>

### Traduzir termo de consentimento PJ para Inglês

**Issue:** #158

- Perguntar para o Bruno sobre a questão legal para empresas estrangeiras (@muriloviana)
- Vamos traduzir os termos para inglês

### Solicitar orçamento com Bruno sobre o modelo de contrato e distrato de patrocínio

**Issue:**

- Solicitamos um primeiro orçamento com a Ana Letícia e se faz interessante obter mais um orçamento para tal serviço.

### Publicação do Fundo de Inclusão

**Issue:** #151

- Onde publicar o texto?
  - Sugestão: https://python.org.br no menu superior "APyB"
- Anunciar fundo e valores disponíveis: R$102.160,73
  - Saldo da Python Brasil 2021 - R$ 204.321,45 - https://2021.pythonbrasil.org.br/prestacao-contas

### Prêmio Dornéles Jean

**Issue:** #103

- Vamos escrever nossas indicações no formulário divulgado
- Discutiremos os nomes quando os quatro diretores estiverem presentes
- Vamos procurar fornecedores locais para confecção das placas (@tiidadavena)

### TW requisitou boleto para pagar o patrocínio da PyBR

**Issue:** https://github.com/pythonbrasil/pybr2022-org/issues/197

- Perguntar para TW se podemos receber o patrocínio via TED
- Caso não dê certo, analizar possibilidade de usar serviço de boletos do BB ou Pagseguro

### Palestra APyB na Python Brasil 2022

**Issue:** #124
- Fechar o dia/duração/local
- Adicionar tópicos no doc https://hackmd.io/2u-A7kOFTVehAv3VtpciuQ

### Organizar Assembleia Geral 2022

**Issue:** #11
- Apresentação de proposta de cidade-sede por vídeo ou online durante a assembléia, devido uma possível baixa quantidade de participantes
  - Avaliar e definir infra necessária
- Quantidade mínima de 11 associados e associadas para que a assembléia ocorra, segundo estatuto.
- Fechar dia/duração/local

### Atualizar documentação de como emitir Nota Fiscal

**Issue:** #159
<Discussão>

- Começamos a documentar como emitir NF para PF, e ficamos de adicionar no mesmo documento os passos para a emissão de NF para PJ: [Link do rascunho](https://docs.google.com/document/d/1PyOWtEtKUCT_ej3Sm3qLpe5AUS7dcZD3MllA-6yPDl0/edit?usp=sharing)

### Incluir exemplo de transação parcialmente ofuscada no termo de consentimento PF

**Issue:** #<número-da-issue>
<Discussão>

- [ ] Discussão sugerida por Renne: https://github.com/apyb/comunidade/discussions/37

### Domínios da APyB

**Issue:** #<número-da-issue>

- Após discussão issue [#comunidade/32](https://github.com/apyb/comunidade/discussions/32), verificamos que temos algumas limitações nas configurações dos domínios dos eventos, atualmente localizado no Configr.
- Precisamos verificar o que tem no Configr, para entendermos melhor a situação atual.
- Surgiu a ideia de migrar toda a estrutura atual para a Cloudflare

### Cadastro de favorecidos para recebimento de TED

**Issue:** #

- Com a quantidade de pagamentos feitos no mês atual, excedemos o limite do montante de transações. Dito isso, precisamos cadastrar cada novo favorecido e "liberar" o cadastro com outro usuário da conta bancária diferente de quem cadastrou.

**Comment by tiidadavena** [comment]
#11

**Comment by tiidadavena** [comment]
#150

**Comment by tiidadavena** [comment]
#151

**Comment by tiidadavena** [comment]
#124

**Comment by rougeth** [comment]
Traduzir termo PJ

**Comment by muriloviana** [comment]
> Traduzir termo PJ

https://github.com/apyb/tarefas/issues/158

**Comment by muriloviana** [comment]
https://github.com/apyb/tarefas/issues/159
