### ISSUE TITLE
Publicação do Fundo de Inclusão

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#151]
**Atividades**

Tendo em vista que faltam 60 dias para a Python Brasil, a necessidade de disponibilização de recursos para levar pessoas de grupos subpreresentados a comparecerem na Python Brasil 2022.

[ ] Revisão Final e Validação do Fundo
[ ] Handoff para a AfroPython e para PyLadies Brasil  
[ ] Divulgação nas redes da APyB e Python Brasil '22

**Comment by tiidadavena** [comment]
Texto final para avaliação da diretoria: https://github.com/apyb/comunidade/discussions/19#discussioncomment-3416775

**Comment by tiidadavena** [comment]
Sugestão de texto de divulgação pela APyB: https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/rJgZDzZki/edit

**Comment by tiidadavena** [comment]
Sugestão de arte: https://www.canva.com/design/DAFKDtTbD6I/vnrsApWqmzjZmSfubunYRg/edit?utm_content=DAFKDtTbD6I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by tiidadavena** [comment]
> Sugestão de texto de divulgação pela APyB: https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/rJgZDzZki/edit

Texto atualizado com a inserção do site do Fundo.

**Comment by tiidadavena** [comment]
Modelo de publicação via Thread no Twitter: 
![image](https://user-images.githubusercontent.com/12106738/187698091-36b9fe04-07b0-4be8-aacd-7a9d66378062.png)

**Comment by rougeth** [comment]
> ...propuseram a destinação dos valores excedentes
propuseram parte dos valores excedentes

> ...redigiram os termos, debateram e avaliaram os termos do fundo.
debateram, avaliaram e definiram os termos do fundo.

Última coisa, o formulário está no site da Python Brasil, não na wiki (onde estão as regras).
------- Original Message -------

**Comment by tiidadavena** [comment]
![Post - Fundo para Inclusão(1)](https://user-images.githubusercontent.com/12106738/188180897-0df8c051-573b-4a9e-bb08-5bc76d05402d.png)

**Comment by tiidadavena** [comment]
Publicação realizada no Twitter, no Github Discussions e no Google Groups.

**Comment by tiidadavena** [comment]
Ajuste no texto da divulgação via Google Groups

**Comment by tiidadavena** [comment]
Realizada postagem com o texto corrigido.
