### ISSUE TITLE
Mover repositórios relacionados a APyB para @apyb organização

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#16]
Vários repositórios na organização [pythonbrasil](https://github.com/pythonbrasil/) são estritamente relacionados a APyB, e precisam ser migrados para a [organização da APyB](https://github.com/apyb). Precisamos levar em consideração a necessidade desses repositórios, e arquivar aqueles que não fazem mais sentido.

Ao migrar um repositório de uma organização para outra, o link original se mantém, mas redirecionando para a nova url.

- [x] https://github.com/pythonbrasil/estatuto (migrado)
- [x] https://github.com/pythonbrasil/associados (migrado)
- [x] https://github.com/pythonbrasil/apyb (migrado)
- [x] https://github.com/pythonbrasil/apyb-request-nfe (deletado)
- [x] https://github.com/pythonbrasil/apyb.gerenciamento (migrado e arquivado)
- [x] https://github.com/pythonbrasil/apyb.conference (arquivado)
- [x] https://github.com/pythonbrasil/apyb.papers (arquivado)
- [x] https://github.com/pythonbrasil/apyb.pythonbrasil (arquivado)
- [x] https://github.com/pythonbrasil/apyb.registration (arquivado)

## Como migrar?
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by rougeth** [comment]
[pythonbrasil/apyb-request-nfe](https://github.com/pythonbrasil/apyb-request-nfe)
Repositório arquivado, porém, acho que devemos excluí-lo. Não tem nada além dos arquivos [.gitignore](https://github.com/pythonbrasil/apyb-request-nfe/blob/master/.gitignore) e [LICENSE](https://github.com/pythonbrasil/apyb-request-nfe/blob/master/LICENSE).

**Comment by muriloviana** [comment]
Estou de acordo em excluir o repositório [pythonbrasil/apyb-request-nfe](https://github.com/pythonbrasil/apyb-request-nfe) 👍

**Comment by rougeth** [comment]
[pythonbrasil/apyb.conference](https://github.com/pythonbrasil/apyb.conference)
[pythonbrasil/apyb.papers](https://github.com/pythonbrasil/apyb.papers)
[pythonbrasil/apyb.pythonbrasil](https://github.com/pythonbrasil/apyb.pythonbrasil)
[pythonbrasil/apyb.registration](https://github.com/pythonbrasil/apyb.registration)

São todos da mesma época, 2011/2012. Acredito que são pacotes que foram usados para os sistemas da Python Brasil daquele ano (cadastro de palestrantes, inscrição, etc). Arquivados, mas não migrados, já que acho que são repositórios relacionados ao evento.

**Comment by rougeth** [comment]
[pythonbrasil/apyb.gerenciamento](https://github.com/pythonbrasil/apyb.gerenciamento) (migrado e arquivado)

Esse repositório foi usado durante a gestão de 2018/2019 para manter controle das tarefas que precisavam ser feitas.

Muitas das issues abertas ainda fazem sentido e precisam ser migradas, então criei uma a issue #18 aqui para não esquecermos.

**Comment by rougeth** [comment]
[pythonbrasil/apyb](https://github.com/apyb/apyb)

>  Novo site da Associação Python Brasil 

Última mudança foi em novembro de 2021: atualização das dependências do projeto. Antes disso, só em 2018, quando projeto foi criado.

Migrei o projeto para /apyb, mas não tenho contexto suficiente para saber o que fazer com ele.
