### ISSUE TITLE
Fim da edição gratuita legada do G Suite [01/05/2022]

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#17]
Os emails @python.org.br são gerenciados em uma conta legada do G Suite. O Google anunciou o fim do plano legado e gratuito, e que as contas existentes precisarão ser migradas para os planos pagos.

---

⚠️ A edição gratuita legada do G Suite **não estará mais disponível a partir de 1º de maio de 2022**. A partir de 1º de maio, o Google fará a transição para o Google Workspace, que poderá ser usado gratuitamente até 1º de julho de 2022.

---

Aparentemente existe um plano para organizações sem fins lucrativos:

> Descontos para escolas e organizações sem fins lucrativos
>
> Talvez você tenha direito ao upgrade para a edição Education ou Nonprofits. Se você já usa uma dessas edições sem custos, pode continuar o uso sem mudanças no serviço.

Anúncio oficial: https://support.google.com/a/answer/2855120?hl=pt

**Comment by tiidadavena** [comment]
A solução que vejo a curto prazo é o [Google for Nonprofits](https://www.google.com/nonprofits/).
![image](https://user-images.githubusercontent.com/12106738/155035986-cee213d3-3958-4af6-a3a9-0cfbff02432a.png)


O recurso que vi maiores limitações foi o de gravação de reunião, mas ele permite customizar os emails: https://www.google.com/nonprofits/workspace/compare/

**Comment by rougeth** [comment]
Podemos tentar já migrar para nonprofits e vamos analisando se comporta nosso uso. Posso ir atrás disso @apyb/diretoria?

**Comment by tiidadavena** [comment]
Lista de documentações para serem enviadas para a Tech a fim de comprovar a organização social:

---
Os passos para se ter acesso aos benefícios TechSoup Brasil, são:
1. Registrar um usuário de e-mail.
2. Fazer o Cadastro da Organização Social.
3. Enviar os documentos para a equipe técnica da TechSoup Brasil (Pendente)

Os documentos necessários são:
a. Comprovante de inscrição no CNPJ (do site da Receita Federal).
b. Cópia do estatuto social original (assinaturas autenticadas em cartório)

**Comment by tiidadavena** [comment]
Email enviado para a Techsoup com o último Comprovante de Inscrição mais atualizado e a última versão do Estatuto Social  com firma reconhecida.

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/162073972-c4348cf2-4793-4c33-a897-d6f54060e800.png)
Techsoup deferiu a candidatura da APyB. Pediram para aguardar em prazo de 24h o envio do código para iniciar o processo de transferência.

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/162968757-e190fbce-2052-4d9c-aa5a-38760fcdb17b.png)
Token gerado na TechSoup e foi submetida a solicitação de migração de conta do G Suite para o Google for Nonprofits, e, apesar da análise levar até 3 dias úteis, já iniciei o processo de solicitação do Youtube e do  Google Analytics.

**Comment by rougeth** [comment]
<img width="578" alt="Screenshot 2022-04-29 at 20 45 34" src="https://user-images.githubusercontent.com/431892/166059379-1fcedbf7-73c6-47dc-810e-960a74817191.png">
