### ISSUE TITLE
Realizar cadastro na CADASTUR

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#19]
https://github.com/pythonbrasil/pybr2022-org/issues/62

Um dos dados requeridos no regulamento do centro de convenções [Vasco Vasques](http://www.amazonastur.am.gov.br/wp-content/uploads/2020/03/Regulamento-de-Uso-Regimento-Interno-CCA-1.pdf), é o cadastro no CADASUR.

> O QUE É O CADASTUR?
> 
> Cadastur é o sistema de cadastro de pessoas físicas e jurídicas que atuam no setor de turismo.
> O cadastro garante diversas vantagens e oportunidades aos seus cadastrados e é também uma importante fonte de consulta > para o turista.
>
> É executado pelo Ministério do Turismo, em parceria com os órgãos oficias de turismo, nos 26 estados e no Distrito Federal.
>
> O CADASTRO É OBRIGATÓRIO?
> 
> Sim, conforme a Lei nº 11.771, de 17 de setembro de 2008, o cadastro é obrigatório para:
> ·         Acampamentos Turísticos;
> ·         Agências de Turismo;
> ·         Meios de Hospedagem; 
> ·         Organizadoras de Evento;
> ·         Parques Temáticos;
> ·         Transportadoras Turísticas;

https://cadastur.turismo.gov.br/hotsite/#!/public/duvidas-frequentes/inicio 

Estou na dúvida se esse cadastro se aplica a APyB, já que nós não atuamos no setor de turismo.

**Comment by rougeth** [comment]
Marcando como bloqueada, já que estão confirmando a necessidade do cadastro, considerando que a APyB é uma associação sem fins lucrativos e que está cadastrada como:
- Atividade Principal: 94.99-5-00 - Atividades associativas não especificadas anteriormente
- Atividade Secundária: 94.93-6-00 - Atividades de organizações associativas ligadas à cultura e à arte

**Comment by rennerocha** [comment]
@rougeth houve a algum tempo uma discussão sobre a inclusão de CNAE de organização de Eventos (8230-0/01 SERVIÇOS DE ORGANIZAÇÃO DE FEIRAS, CONGRESSOS, EXPOSIÇÕES E FESTAS) como uma das atividades da APyB. Um patrocinador de um evento que estava organizando a alguns anos atrás não queria aceitar a Nota Fiscal de patrocínio usando o CNAE de Treinamentos (esses dois CNAE que você passou são só os principais, a APyB possui alguns outros) e que o correto seria usar esse de organização de eventos (já que realmente organizamos eventos).

De acordo com o site, não necessitamos o cadastro, mas eu acho que adicionar esse CNAE para a APyB faria muito sentido, pois a organização de eventos é sim uma atividade que realizamos e precisamos emitir as Notas Fiscais adequadas quando fazemos isso.

https://cadastur.turismo.gov.br/hotsite/#!/public/se-cadastrar#ancoraSeCadastrar

**Comment by muriloviana** [comment]
Sobre a issue em si, comprovamos junto a AmazonasTur, gestora do local do evento, que a APyB é uma instituição sem fins lucrativos, logo nos encaixamos no parágrafo 7 e 8 do artigo único do regulamento de uso do Vasco Vasques, o que não necessita de cadastro no CADASTUR.
