### ISSUE TITLE
Reunião: 21/02/2022

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#20]
# Reunião

- Data: 21/02/2022
- Participantes:
  - Ana
  - Juliana
  - Marco
  - Murilo

## Ata

- Primeiro e-mail da newsletter
    - @rougeth  Criar template para a newsletter
    - @rougeth  Enviar e-mail de março
- Local apropriado para documentação da APyB
    - @rougeth  Criar /apyb/wiki
- Conversar sobre andamento da Python Brasil 2023.
    - @anadulce  Conversar com big kahunas da Python Brasil 2023 sobre a realização, ou não, do evento
- Decidir sistema de compartilhamento de senhas:
    - @anadulce Testar funcionalidade de autenticação em dois fatores
- Portal de transparência (extratos públicos da conta da APyB)
    - @muriloviana  Puxar no discussions quais dados devem ser anonimizados. Lembrar de colocar uma data limite para uma conclusão
- Prêmio Dorneles: @anadulce vai procurar saber se os prêmios foram entregues

**Comment by rougeth** [comment]
- Conversar sobre andamento da Python Brasil 2023.

**Comment by anadulce** [comment]
Decidir sistema de compartilhamento de senhas.

**Comment by rougeth** [comment]
Ata atualizada na descrição da issue.
