### ISSUE TITLE
Atualizar Estatuto da APyB em cartório

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#214]
Verificando no Google Drive da Associação, percebi que a última alteração registrada em cartório do Estatuto foi feita em [2013](https://drive.google.com/file/d/0B7AZ7Zt9Vp36ZG9EdEZIYTlXbTA/view?usp=sharing&resourcekey=0-ZSDq3HgfzvKizFg5TR6rbw). De lá pra cá, algumas alterações foram feitas no repo do Estatuto: https://github.com/apyb/estatuto.

Para que essas alterações sejam de fato concretizadas, precisamos registrá-las em cartório.

**Comment by naanadr** [comment]
Foi dada a sugestão na reunião https://github.com/apyb/tarefas/issues/521 de aproveitar a PyBR 2024, e na reunião da associação apresentar o estatuto atual e colocar para votação. Se todos estiverem de acordo, ir no cartório com a ata dessa reunião e atualizar o estatuto.

É preciso pesquisar se podemos fazer a atualização do estatuto apenas no cartório de Caxias, ou pode ser em qualquer outro. E o que precisa levar para fazer a atualização do estatuto.

**Comment by naanadr** [comment]
O estatuto que tem disponível no cartório é esse [aqui](https://drive.google.com/file/d/1Qh9PUOCzj7Y8qVL_uwyTM-HnM3qg-QjU/view?usp=sharing), a única diferença dele em relação ao estatuto que está disponível para consulta [aqui](https://github.com/apyb/estatuto/blob/master/README.rst), são os artigos 43 e 44 que foram removidos do estatuto novo. 

@apyb/conselho-deliberativo vocês acham que vale a pena alterar o estatuto do repositório sem esses dois últimos artigos?

**Comment by rennerocha** [comment]
@naanadr 

O estatuto que deveria estar disponível no repositório, que é o que as pessoas associadas e o público geral tem acesso e usa como referência, deveria ter o **texto exato do estatuto que está registrado em cartório**. Para cada alteração, podemos criar uma tag no repositório para termos de maneira fácil o histórico de alterações dele.

Se a remoção dos artigos 43 e 44 foi aprovada em alguma Assembleia, mas não foi registrada ainda em cartório, esses artigos na prática continuam válidos, já que a alteração do Estatuto precisa ser registrada em cartório para que se torne válida.

**Comment by rennerocha** [comment]
@naanadr 
Pelo que entendi, a remoção dos artigos 43 e 44 já foi aprovada em alguma Assembleia. Se isso aconteceu, a Ata dessa Assembleia já deveria ter sido registrada junto com o Estatuto modificado. Caso essa remoção não tenha passado por Assembleia, esse ano podemos colocar como item de votação, fazer a aprovação e aí registrar o Estatuto atualizado e então deixar essa nova versão aqui no repositório também para consulta.

Respondendo outra pergunta:

> É preciso pesquisar se podemos fazer a atualização do estatuto apenas no cartório de Caxias, ou pode ser em qualquer outro. E o que precisa levar para fazer a atualização do estatuto.

Sim, você precisa registrar no cartório de Caxias, já que a Associação tem sede em Caxias. Porém, é possível que você consiga fazer todo o processo online, assinando todos os documentos com assinatura digital do gov.br. Eu fiz o registro de Ata, Eleição e alteração de Estatuto do Laboratório Hacker de Campinas sem sair de casa. Só precisa confirmar com o cartório, se eles aceitam receber a documentação dessa maneira (é bem provável que sim).

**Comment by naanadr** [comment]
@rennerocha não salvaram a ata de 2019 registrada em cartório no driver 😢 , mas [aqui](https://drive.google.com/file/d/1Qh9PUOCzj7Y8qVL_uwyTM-HnM3qg-QjU/view?usp=sharing) tem a versão do estatuto que está disponível no cartório. Pelo o que eu pude entender do [rascunho da ata](https://docs.google.com/document/d/14JpcqTrjcsF1Bij76IiR05_JAfBXll0ycxPwilbb9Wg/edit?usp=sharing) que o @sergiomario fez, essa alteração foi votada em 2019.

Talvez o @mazulo ou o @sergiomario tenham a ata de 2019 registrada em cartório 🙏🏼 Mas de toda forma, para adiantar vou abrir um PR no repositório do estatuto com a remoção dos artigos 43 e 44.

**Comment by lucianoratamero** [comment]
oi, pessoal! desculpa por não ter visto isso antes. =/
100% concordo com o @rennerocha , o que tá no cartório deve ser uma cópia exata do que temos no repositório. inclusive, já dei minha revisão no PR que faz a alteração, aprovando a proposta.

um detalhe é que eu não vi essa discussão por não estar acostumado a receber notificações pelo github, e sinto que esse problema pode não ser só meu. por conta disso, além de pedir desculpas por não ter visto essa discussão antes, queria perguntar se temos outros canais para esse tipo de discussão, ou se é mais coisa minha de resolver minhas configurações de notificação mesmo. :]

talvez isso seja até pauta de discussão na própria assembléia e de possível mudança no estatuto, para formalizarmos esses canais de comunicação melhor no início das gestões - até porque sinto falta de ter comunicação por mensagem instantânea com as outras pessoas membras de conselho/diretoria. acham que essa discussão seria interessante?

**Comment by mazulo** [comment]
Oi pessoal, desculpe a demora. Só agora que também recebi o
e-mail/notificação sobre essa thread. Como o Mário Sérgio falou, esse
documento que ele linkou é o conteúdo da alteração do estatuto. O 2020 no
nome do arquivo foi somente porque foi quando o todo o processo foi
finalizado (em meados de Janeiro de 2020). Mas ela aborda sobre o ano de
2019. Agora sobre o conteúdo da ATA, eu não saberia dizer. Aparentemente
perdi acesso ao drive da APyB, então não consigo checar se ela foi salva
com algum outro nome (já que todo e qualquer outro documento referente a
APyB era salvo somente lá).

Porém, se não me engano, da última vez que me perguntaram sobre (acho que
foi a Alyne no Telegram), eu havia enviado para ela o documento da ata
(acho que o nome do arquivo era *ATA 14_ESTATUTO*), o que tem grandes
chances de ser esse que estaria faltando.

*Patrick Mazulo de Brito*

   - *Software Engineer at* https://carta.com/
   - *Former President of* APyB <https://python.org.br/apyb/>
   - *Code Streamer in* https://www.twitch.tv/dunderlabs



*GitHub: https://github.com/mazulo <https://github.com/mazulo>*
*LinkedIn: https://br.linkedin.com/in/mazulo
<https://br.linkedin.com/in/mazulo>*

**Comment by naanadr** [comment]
Obrigada pessoal, o estatuto do repositório está agora refletindo o que consta no cartório.

**Comment by naanadr** [comment]
> talvez isso seja até pauta de discussão na própria assembléia e de possível mudança no estatuto, para formalizarmos esses canais de comunicação melhor no início das gestões - até porque sinto falta de ter comunicação por mensagem instantânea com as outras pessoas membras de conselho/diretoria. acham que essa discussão seria interessante?

@lucianoratamero o nosso canal de comunicação é o grupo de e-mail `apyb-condir@`, tem as issues aqui no `/tarefas` e threads no `/discussion` . No caso, a maioria das comunicações é no github 😄, para deixar tudo o mais transparente possível.

Sobre um grupo de mensagens instantâneas, você pode puxar isso junto com os outros conselheiros, ou abrir uma thread no [discussion](https://github.com/apyb/comunidade/discussions) trazendo esse assunto, ou adicionar como ponto de [pauta](https://github.com/apyb/comunidade/discussions/128) da próxima assembleia. A diretoria atual entende que os conselhos devem ser independente na forma que se organizam ❤️ .
