### ISSUE TITLE
Revisar acesso a lista apyb-condir@googlegroups.com

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#26]
- Alterar dono da lista para um email @python.org.br
- Rever acessos

**Comment by rougeth** [comment]
Email tecnologia no @python.org.br é o único dono da lista e apenas a direção está com poderes de moderação.

**Comment by muriloviana** [comment]
Tava dando uma olhada na lista, parece que precisamos adicionar as pessoas integrantes dos conselhos. Confere? Se sim, precisamos ir atrás dos email de cada uma.
