### ISSUE TITLE
Comentários nos vídeos do YouTube

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#27]
Percebi que existem vários vídeos (pybr14 em particular) com comentários abertos. Como nós não conseguiremos moderar os comentários, precisaremos remover e bloqueá-los.

**Comment by cuducos** [comment]
> precisaremos remover e bloqueá-los

Fiquei em dúvida sobre esse “precisamos” — eu sei que deve ter um monte de coisa inútil lá. Mas como isso afeta a APyB?

**Comment by rougeth** [comment]
Entendo que qualquer problema, como infrações ao código de conduta, em ambientes administrados pela APyB, mesmo que relacionados a eventos que já aconteceram, são de responsabilidade da APyB.

**Comment by cuducos** [comment]
Boa!

**Comment by rougeth** [comment]
Desabilitei comentários em todos os 1014 vídeos do canal. Apesar de não ter API disponível para isso, UI permite atualizar todos os vídeos de uma só vez 😮‍💨.
