### ISSUE TITLE
Boletim Informativo - Outubro, 2022

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#276]
#### Template

```
Título: Boletim Informativo, {Mês}, {Ano} 

## Destaques
#COMENTÁRIO: Destacar os tópicos que tiveram maior impacto na APyB ou comunidade.

### {Título}
{Breve descrição do tópico, não precisa entrar em detalhes}

Detalhes: {Link}

## Outros tópicos
- {Título} - {Link}

[@apyb/diretoria](https://github.com/orgs/apyb/teams/diretoria) 👋
```

Para revisão do boletim:
- [ ] Algum tópico não mencionado?
- [ ] Algum tópico que merece destaque?
- [ ] Algum tópico que não merece destaque?
- [ ] Alguma contribuição da comunidade que deve ser listada?

Uma vez com o boletim revisado:
- [ ] Criar novo anúncio no [@apyb/comunidade](https://github.com/apyb/comunidade/discussions/categories/an%C3%BAncios) com boletim
- [ ] Enviar boletim na lista de e-mail da associação
- [ ] Divulgar link da postagem do anúncio no Twitter da APyB

**Comment by tiidadavena** [comment]
https://github.com/apyb/comunidade/discussions/43

**Comment by tiidadavena** [comment]
https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/H1glKHZBo/edit

**Comment by muriloviana** [comment]
https://github.com/apyb/tarefas/issues/123

Reembolsos Python Sul 2020

Finalizando pendências do evento de 2020, para então realizar o fechamento do evento de 2022.

**Comment by tiidadavena** [comment]
Issue fechada retroativamente pois a publicação foi feita no dia 08/11.
