### ISSUE TITLE
Migrar tarefas no Trello para este respositório

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#3]
## Descrição

As pessoas diretoras da chapa 20/21 estava usando Trello para manter registros das tarefas que estavam trabalhando. Precisamos 1) analisar os itens pendentes e em andamento e 2) migrar para esse repositório o que decidirmos dar continuidade.

**Comment by muriloviana** [comment]
Board do Trello revisado, e migrado 👍

**Comment by rougeth** [comment]
Reabrindo, acabou faltando revisar a coluna `Doing` no Trello.
