### ISSUE TITLE
Boletim Informativo - Dezembro, 2022

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#300]
#### Template

```
Título: Boletim Informativo, {Mês}, {Ano} 

## Destaques
#COMENTÁRIO: Destacar os tópicos que tiveram maior impacto na APyB ou comunidade.

### {Título}
{Breve descrição do tópico, não precisa entrar em detalhes}

Detalhes: {Link}

## Outros tópicos
- {Título} - {Link}

[@apyb/diretoria](https://github.com/orgs/apyb/teams/diretoria) 👋
```

Para revisão do boletim:
- [ ] Algum tópico não mencionado?
- [ ] Algum tópico que merece destaque?
- [ ] Algum tópico que não merece destaque?
- [ ] Alguma contribuição da comunidade que deve ser listada?

Uma vez com o boletim revisado:
- [ ] Criar novo anúncio no [@apyb/comunidade](https://github.com/apyb/comunidade/discussions/categories/an%C3%BAncios) com boletim
- [ ] Enviar boletim na lista de e-mail da associação
- [ ] Divulgar link da postagem do anúncio no Twitter da APyB

**Comment by tiidadavena** [comment]
- Resumo das principais atividades realizadas durante o ano
- Apresentar as issues fechadas
- Desejar boas festividades

**Comment by tiidadavena** [comment]
Segue texto para avaliação: https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/rkRYkamqi/edit

**Comment by anadulce** [comment]
Teste :)
/apyb/tarefas#2
#52
/apyb/comunidade/16

**Comment by anadulce** [comment]
/apyb/comunidade/16
/apyb/comunidade/discussions#9

**Comment by tiidadavena** [comment]
Postagem realizada nas redes sociais no dia 17/01/2023.
