### ISSUE TITLE
Boletim Informativo - Janeiro, 2023

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#304]
#### Template

```
Título: Boletim Informativo, {Mês}, {Ano} 

## Destaques
#COMENTÁRIO: Destacar os tópicos que tiveram maior impacto na APyB ou comunidade.

### {Título}
{Breve descrição do tópico, não precisa entrar em detalhes}

Detalhes: {Link}

## Outros tópicos
- {Título} - {Link}

[@apyb/diretoria](https://github.com/orgs/apyb/teams/diretoria) 👋
```

Para revisão do boletim:
- [ ] Algum tópico não mencionado?
- [ ] Algum tópico que merece destaque?
- [ ] Algum tópico que não merece destaque?
- [ ] Alguma contribuição da comunidade que deve ser listada?

Uma vez com o boletim revisado:
- [ ] Criar novo anúncio no [@apyb/comunidade](https://github.com/apyb/comunidade/discussions/categories/an%C3%BAncios) com boletim
- [ ] Enviar boletim na lista de e-mail da associação
- [ ] Divulgar link da postagem do anúncio no Twitter da APyB

**Comment by tiidadavena** [comment]
- Relembrar do pagamento feito ao pessoal da arquitetura para a PyBR 2023
- Relembrar pessoas de se associarem (Efetivo/Estudante)
- Estamos acompanhando as organizações das conferências PyNE e PyBR 2023

**Comment by anadulce** [comment]
Também estamos acompanhando a organização da PyNorte

**Comment by tiidadavena** [comment]
> Também estamos acompanhando a organização da PyNorte - que inclusive, estavam procurando voluntários, e acho que poderíamos divulgar aqui :)

Além do PyNorte, os outros eventos tb estão buscando pessoas voluntárias ou só devemos qd as equipes derem o aval de divulgação?

**Comment by anadulce** [comment]
> > Também estamos acompanhando a organização da PyNorte - que inclusive, estavam procurando voluntários, e acho que poderíamos divulgar aqui :)
> 
> Além do PyNorte, os outros eventos tb estão buscando pessoas voluntárias ou só devemos qd as equipes derem o aval de divulgação?

Até onde eu saiba, os outros eventos não estão procurando organizadores, mas podemos perguntar antes de mandar o boletim :)

**Comment by tiidadavena** [comment]
Texto publicado nos dia 13/02/2023.
