### ISSUE TITLE
Alterar email da conta do Ultradox

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#31]
## Descrição

Atualmente a conta de cadastro da nossa conta do Ultradox está vinculada ao henrique@python.org.br. Seria interessante alterar para outro email não vinculado a uma pessoa especificamente.

**Comment by naanadr** [comment]
E-mails agora serão enviados pelo `noreply`. Mais contexto na issue #596 .

![image](https://github.com/apyb/tarefas/assets/21251472/fbf8592c-4976-4227-b8bc-0506d39c5955)

**Comment by rougeth** [comment]
Muito bom @naanadr, obrigado!
