### ISSUE TITLE
Criação de Roadmap de Comunicação

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#312]
Visando guiar a condução das atividades de comunicação, o Roadmap serviria de guia para apoiar as futuras iniciativas de Comunicação.

O link de documentação está disponível aqui: https://docs.google.com/document/d/1Ugz1OE3f7q_gDgCv2eQ6MtmyXgMC9gV9Cb1hJkWeqGA/edit#

**Comment by naanadr** [comment]
@tiidadavena esse roadmap seria algo mais geral que ficaria na wiki, ou essa issue foi para dar visibilidade para o seu roadmap do ano de 2023? 🤔

**Comment by tiidadavena** [comment]
> @tiidadavena esse roadmap seria algo mais geral que ficaria na wiki, ou essa issue foi para dar visibilidade para o seu roadmap do ano de 2023? 🤔

Isso, foi pra dar visibilidade às atividades de Comunicação do ano passado.
