### ISSUE TITLE
Criação do projeto no github pra pybr2024

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#318]
Vide https://github.com/pythonbrasil/pybr2023-org :)

**Comment by rougeth** [comment]
- Criei o time [@pybr2024-org](https://github.com/orgs/pythonbrasil/teams/pybr2024-org) e adicionei você @biancarosa como *owner* do grupo.
- Criei o repositório [pythonbrasil/pybr2024-org](https://github.com/pythonbrasil/pybr2024-org) e coloquei o time @pybr2024-org como mantenedor por padrão.
- Aproveitei e já fiz o mesmo com o repositório do site [pythonbrasil/pybr2024-site](https://github.com/pythonbrasil/pybr2024-site/)
