### ISSUE TITLE
Documentar prosposta de utilização do sistema financeiro da APyB por parte das PyLadies

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#32]
Documentar prosposta de utilização do sistema financeiro da APyB por parte das PyLadies, definindo regras, fluxos e processos. Documento precisa ser feito até 29 de março, pois será usado na assembleia das PyLadies.

Ata da primeira reunião: https://github.com/pyladies-brazil/organizacao/issues/84

Deliberar sobre a sugestão de montantes remanescentes de eventos organizados por PyLadies terem caixa revertido para o fundo das PyLadies Brasil. Neste momento, a regra vigente determina que todo o montante remanescente de eventos será destinado ao caixa da APyB;

**Comment by anadulce** [comment]
Primeira versão da documentação: https://hackmd.io/@anadulce/proposta_apyb_pyladies
