### ISSUE TITLE
Conferir configurações do domínio relacionadas ao e-mail

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#332]
Pessoas reportaram estarem recebendo alertas de falha de autenticação de e-mails enviados por meio do @python.org.br:

> This email has failed its domain’s authentication requirements. It may be spoofed or improperly forwarded!

https://proton.me/support/email-has-failed-its-domains-authentication-requirements-warning

**Comment by rougeth** [comment]
Autenticação via DKIM configurada.

**Comment by rougeth** [comment]
https://support.freshdesk.com/en/support/solutions/articles/223779-digitally-sign-emails-with-dkim-

**Comment by naanadr** [comment]
@rougeth essa issue já foi resolvida? 🤔

**Comment by rougeth** [comment]
Sim :)
