### ISSUE TITLE
Contactar Canva para criar conta para NGOs

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#35]
Atualmente a APyB não conta com manual de identidade visual nem tampouco com recursos gráficos para garantir a padronização do uso da logo e de outros assets.

Com o intuito de regularizar a identidade visual e criar uma plataforma para padronização de geração de conteúdo, foi levantanda a demanda de criar uma conta em uma plataforma de produção gráfica para a regularização da identidade e marca da APyB.

A nossa primeira opção é o Canva, pois permite a adição e a remoção de emails para usuários temporários, excelente usabilidade e pelos casos de sucesso de uso nas PyLadies Brasil.

*Direcionamentos*

- [ ] Apresentar problemática para o quadro da Diretoria
- [ ] Enviar email para o Canva solicitando abertura de conta
- [ ] Disponibilizar os acessos para a Diretoria

**Comment by tiidadavena** [comment]
De acordo com as diretrizes do Canva, os [critérios de elegibilidade](https://www.canva.com/pt_br/canva-para-ongs/elegibilidade/) para solicitar a conta for Nonprofits necessita do "Certificado de Registro para Associações, Fundações e Organizações da Sociedade Civil de Interesse Público do Ministério da Justiça e Segurança Pública"

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/159785506-bce2c464-5d27-4cb2-bc47-39f1d26e02dd.png)

**Comment by rougeth** [comment]
Temos o CADASTRO NACIONAL DA PESSOA JURÍDICA no Drive - https://drive.google.com/file/d/1lIJLqb01Y46ojo05yix1fluGQAkf6Su9/view?usp=sharing

Está atualizado, gerei um novo documento no site da receita:
http://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/Cnpjreva_Comprovante.asp

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/161646343-1af7abb7-ffcb-47f3-b5c4-dfefc9cc1b1e.png)
Documentos enviados com prazo para retorno entre 7 a 10 dias.

**Comment by tiidadavena** [comment]
![image](https://user-images.githubusercontent.com/12106738/162012033-edb33ec1-45ec-4915-9879-b49add64c7d5.png)
A conta NGO da APyB foi aprovada!

**Comment by tiidadavena** [comment]
Acessando a conta, dá para verificar que estamos conseguindo acessar recursos Pro, como gerenciador de marca (onde podemos subir a paleta da id visual, e as variações de logos).

![image](https://user-images.githubusercontent.com/12106738/162012804-76a6f3a4-559c-451d-9aa5-0cdf519db7fa.png)

**Comment by tiidadavena** [comment]
Acredito que as configurações subquentes são aplicáveis para outro contexto, portanto devem ser rastreadas em outra issue.
