### ISSUE TITLE
Identidade visual da APyB

### ISSUE THREAD

**Issue by anadulce** [apyb/tarefas#36]
Solicitar o contato das pessoas que estão desenvolvendo a identidade visual dos eventos vigentes e realizar orçamentos;

**Comment by tiidadavena** [comment]
Em conversa com Tai Valois, ela aceitou o convite e pediu para incluir na call o Klayton Renan que também foi responsável pela id visual da PyBR 2022.

Ela também mostrou disponibilidade para participar de uma reunião no dia 28/03 às 19h (i.e. slot de reunião da APyB). Para a reunião será necessária a criação do briefing com as demandas, mas vou criar uma issue em separado e referenciar aqui.

**Comment by tiidadavena** [comment]
Issue da tarefa de criação do briefing: https://github.com/apyb/tarefas/issues/38

**Comment by rougeth** [comment]
[Proposta de trabalho](https://github.com/apyb/tarefas/files/8400407/Proposta.de.Investimento.-.Identidade.Visual.pdf) discutida na reunião do dia 21 de março.

**Comment by tiidadavena** [comment]
Email enviado usando o email comunicacao@py... com a anexação do briefing atualizado para Tai e Klayton solicitando a atualização do orçamento anterior.

**Comment by tiidadavena** [comment]
Novo orçamento recebido na última semana a partir dos dados apresentados no briefing.

**Comment by tiidadavena** [comment]
Últimos desdobramentos registrados nas issues: #38 #66
