### ISSUE TITLE
Nota Fiscal: python brasil 2023 - emissão de nota fiscal para a Globo

### ISSUE THREAD

**Issue by lipemorais** [apyb/tarefas#365]
#### Solicitação de Emissão de Nota Fiscal
- Evento: **python brasil 2023**
- Descrição: **Emissão de nota fiscal para a Globo**
- Valor: **R$5000**
- Demais dados enviados por e-mail (apyb-condir@).
![image](https://github.com/apyb/tarefas/assets/5021565/aa9a6009-a1ff-452a-94e3-9b8b3a187342)

#### Como emitir nota fiscal?
- [Como emitir uma nota fiscal de patrocinio (parte 1)](https://drive.google.com/drive/u/0/folders/0B_CQOAVUY5bRZC0wLXlyRTJnZjQ?resourcekey=0-vVGF7hbDK0lsuD1GK2pMUw)
- [Como emitir uma nota fiscal de patrocinio (parte 2)](https://drive.google.com/file/d/0B7AZ7Zt9Vp36Uk9mNG9lYzlDMUk/view?usp=sharing&resourcekey=0-tt-x0sW7i4WvcrPh6_QPKA)

**Comment by lipemorais** [comment]
Tive o acesso negado aos 2 item nos link no final da mensagem anterior.

**Comment by muriloviana** [comment]
Duplicado #367
