### ISSUE TITLE
Criar issue neste repositório ao gerar um Invoice via Ultradox

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#389]
Quando um invoice é gerada, APyB dir-con recebe um email informando a emissão desta invoice. No entanto, não temos o registro dela neste repositório. O que é bem-vindo para documentar os passos pós emissão, como fechamento de câmbio e entrada do pagamento na conta da APyB.

Precisamos adicionar essa etapa no Ultradox.

**Comment by naanadr** [comment]
Issue foi criada:  https://github.com/apyb/tarefas/issues/1008
