### ISSUE TITLE
Transferir saldo do PagSeguro para conta no Banco do Brasil

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#4]
## Descrição

A conta da APyB no PagSeguro contém saldo que precisa ser transferido para a conta corrente no Banco do Brasil.

**Comment by muriloviana** [comment]
Como já temos acesso a conta do BB, essa issue passa a ficar desbloqueada \o/

**Comment by muriloviana** [comment]
Tentei fazer uma transferência teste, porém é necessário verificar a transação. Para isso precisamos de uma das seguintes opções:

* Confirmar a transação pelo número "(21) *****-4913", o qual não sei a quem pertence.
* Alterar esse número de telefone para o de alguém da nova gestão. Mas para isso, é preciso o acesso ao email vinculado à conta do PagSeguro para confirmar a alteração, o qual não consta no Keybase.

Irei atrás de tais informações, mas gostaria de aproveitar a deixa para adicionarmos essa "transferência de responsabilidade" do PagSeguro no processo de transição da próxima gestão.

**Comment by gabubellon** [comment]
@muriloviana  esse número é do @mazulo

**Comment by muriloviana** [comment]
[Atualização]

1. Conseguimos alterar o telefone de confirmação de transações da nossa conta do PagSeguro, para o meu número (atual diretor financeiro).
2. No dia 02/03, Fizemos uma primeira transferência de teste com um valor baixo, R$1,61 (um real e sessenta e um centavos)  para verificar se daria certo.
3. Aguardamos alguns dias para verificar se o valor seria estornado sabe-se lá por qual motivo (como relatos da gestão anterior rs).
4. Após o período de teste, no dia 08/03, fizemos a primeira transferência no valor de R$10.000,00 (dez mil reais) para a conta do BB.
5. Até o final da semana terminaremos de transferir todo o saldo, pois o limite diário de transferência da nossa conta do PagSeguro é de R$10.000,00 (dez mil reais).

![Screen Shot 2022-03-08 at 14 55 58](https://user-images.githubusercontent.com/6524275/157298251-118a2fe0-b4ad-4848-a962-cc5647cf4022.png)
![Screen Shot 2022-03-08 at 14 54 14](https://user-images.githubusercontent.com/6524275/157298248-173adb8f-6a43-4c0c-b582-c6f298d05171.png)
![Screen Shot 2022-03-08 at 14 53 33](https://user-images.githubusercontent.com/6524275/157298567-0bf094f6-d2fc-47b5-919d-cee496c72da3.png)

**Comment by muriloviana** [comment]
Dinheiro do PagSeguro transferido para a conta do BB.

<img width="914" alt="Screen Shot 2022-03-19 at 12 43 38" src="https://user-images.githubusercontent.com/6524275/159128221-f3b543a8-fc7d-41f1-a184-f1d9f027cf61.png">
