### ISSUE TITLE
Criar um time @apyb/conselho

### ISSUE THREAD

**Issue by gabubellon** [apyb/tarefas#47]
Favor criar times @apyb/conselhodeliberativo e @apyb/conselhofiscal.
Isso pode auxilar quando gostartiamos de marcar ou pedir ação dos membros, assim como @apyb/diretoria

**Comment by rougeth** [comment]
@apyb/conselho-deliberativo e @apyb/conselho-fiscal criados e convites para as pessoas eleitas enviados.

**Comment by rougeth** [comment]
Vou manter a issue aberta até todas as pessoas aceitarem o convite.

**Comment by rougeth** [comment]
Todos os convites aceitos! :)

**Comment by alynnefs** [comment]
@rougeth desculpa te dar trabalho, mas tive problema com o authy (problema de usuário mesmo, tinha perdido a senha) e era recomendado tirar o 2FA pra recuperar. Quando tiver tempo, pode me colocar de volta?

**Comment by rougeth** [comment]
@alynnefs convite enviado!
