### ISSUE TITLE
Revisar contas de e-mail no domínio python.org.br

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#48]
Temos 31 e-mails no domínio python.org.br e a maioria sem uso a vários anos. Precisamos checar o que precisa ser feito backup e então remover as contas que já não fazem mais sentido.

**Comment by naanadr** [comment]
Atualmente temos 16 usuários ativos, e um deles é o `henrique@` . 

O fluxo do ultradox que estava vinculado a esse e-mail já foi migrado para o `noreply@` e o driver vou migrado para o `webmaster@`. Vou esperar alguns meses para arquivar de vez o e-mail `henrique@`. 

Outros 16 e-mails que eram vinculados a pessoas da comunidade foram arquivados pela gestão anterior.

**Comment by naanadr** [comment]
Todos os 17 e-mails que estavam suspensos foram excluídos e os seus drivers migrados para o `webmaster@`

- alvaro@
- cifali@
- erico@
- jean@
- jsbueno@
- list-forward@
- luciano@
- mario@
- osantana@
- petry@
- ramiroluz@
- renato@
- rube@
- ruda.porto@
- taniaa@
- tati_alchueyr@
- trilhas@
