### ISSUE TITLE
Site da associação caiu por falta de pagamento no Heroku

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#49]
Site da associação caiu por falta de pagamento no Heroku. No começo do ano eu troquei o cartão de crédito usado no Heroku (#9), mas acabei precisando gerar um novo cartão e não lembrei de substituí-lo pelo novo número.

Alguns e-mails foram enviados na conta webmaster - 9 de março parece ter sido o primeiro, porém, só ficamos sabendo porque o @gomex avisou no Discord da Python Brasil (obrigado @gomex!).

---

Já atualizei o cartão no Heroku, os pagamentos atrasados foram feitos e o site restabelecido. Próximo passo é identificar o que podemos fazer para que 1) não precisemos da comunidade para saber que algum dos sites da APyB não esteja funcionando, e 2) que a vejamos as notificações importantes enviadas para os e-mails da APyB.

**Comment by gomex** [comment]
Uma ideia seria cadastrar uma conta free do https://uptimerobot.com. Inicialmente teríamos um monitor se o site está funcionando ou não, depois o passo seguinte seria integrar com o discord, ou algo do tipo.

**Comment by gabubellon** [comment]
@rougeth Com a implementação do GSuite For Non Profit daria pra criar um alias/email exclusivo pra isso e ele ser prioritário na caixa de mensagem.
A ideia do @gomex é bem pertinente, ter algum aviso para Discord/Telegram que seja dessas notificações importantes

**Comment by rougeth** [comment]
Criei uma conta no uptimerobot e configurei uma notificação por email que chega na APyB. Valeu pela ajuda @gomex @gabubellon.
