### ISSUE TITLE
Site: PyBR 2024

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#498]
Pessoal, vamos configurar o subdominio da pybr 2024?

2024.pythonbrasil.org.br

pro repo https://github.com/pythonbrasil/pybr2024-site

creio que já esta tudo configurado lá pra aceitar o gh-pages, só mudar os cname's :) 

E daí depois abrimos uma issue pra fazer o redirect / troca do pythonbrasil.org.br pro 2024

**Comment by Perceu** [comment]
@rougeth fiz o deploy no gh-pages e nao bombou sabe me dizer se fiz algo errado ?

**Comment by rougeth** [comment]
Domínio e redirecionamento configurados: https://pythonbrasil.org.br! :D
