### ISSUE TITLE
Cadastrar acesso a conta bancária no Banco do Brasil

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#5]
## Descrição

@anadulce e @muriloviana precisam ter seus acessos cadastrados na conta corrente da APyB no Banco do Brasil. Veremos como eu e @tiidadavena poderemos ter acesso a conta em um segundo momento.

**Comment by muriloviana** [comment]
Atualização: a ata original registrada em cartório da reunião onde a gestão atual foi eleita está em posse da contadora da associação. Ela disse que levará a ata até uma agência do BB na próxima semana (07-11/02/22).

Uma vez que a ata esteja registrada no sistema do BB, eu e a @anadulce podemos solicitar o acesso a conta com uma simples cópia da mesma ata em qualquer agência do BB.
