### ISSUE TITLE
Migrar domínio da Python Nordeste para APyB

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#504]
Conforme discutimos no [/comunidade](https://github.com/apyb/comunidade/discussions/70), criando essa issue para registrar o que vamos precisar fazer durante a migração do domínio.

cc @fabiocerqueira, @naanadr

**Comment by fabiocerqueira** [comment]
Vou comecar o processo de transferencia

**Comment by fabiocerqueira** [comment]
DNS pra urls acima parece normalizado

**Comment by rougeth** [comment]
Todas as edições até 2022 não estão com redirecionamento automático de `HTTP` para `HTTPS`. Isso pode ser feito nas configurações do Github ou no Cloudflare. Acho que seria melhor deixar pronto no Github porque no dia que mudarmos de provedor DNS, não teremos problemas com isso.

Levando em considerando que são sites estáticos, não ter esse redirecionamento não é tão problemático, portanto, prioridade baixa.

**Comment by naanadr** [comment]
@fabiocerqueira tu tinha testado a url com `www`? Porque o redirect do `www.pythonnordeste.org`  não está funcionando. Adicionei umas page rules, mas não parece ter surtido muito efeito.

![image](https://github.com/apyb/tarefas/assets/21251472/7e388afa-772a-4c66-810e-4fd3ccaae20a)
![image](https://github.com/apyb/tarefas/assets/21251472/6a7c82f8-8b19-46ea-8cb5-5de6f93002e4)

**Comment by fabiocerqueira** [comment]
Todas as urls foram testadas durante a migração, eu não tenho mais acesso ao domínio

**Comment by fabiocerqueira** [comment]
Vc pode tentar checar se tem algum entrada nos dns records que tá conflitando

**Comment by fabiocerqueira** [comment]
@naanadr olhando aqui parece que o dominio ainda ta apontando para um redirecionamento no fly.io e esse redirecionamento ta com certificados expirados. 

![image](https://github.com/apyb/tarefas/assets/58733/0de26e09-16ea-4805-adf1-9895373743c6)


Tem duas formas de corrigir isso:

- verificando o certificado(que eu posso ajudar)
- trocando o redirecionamento pra usar so cloudflare

**Comment by naanadr** [comment]
@fabiocerqueira eu não tenho acesso ao fly.io do PyNE, tenho apenas o do PyBR.

@itepifanio / @ryllari vocês tem acesso ao `fly.io` ? Poderiam dar uma olhadinha no certificado? Porque a url `www.pythonnordeste.org.br` aparentemente funcionava antes e agora não pega mais.

**Comment by itepifanio** [comment]
> vocês tem acesso ao `fly.io`?

@naanadr eu não tenho acesso, acredito que a @Ryllari também não :/

> Porque a url www.pythonnordeste.org.br aparentemente funcionava antes e agora não pega mais

Realmente tinha notado esse comportamento após a migração do domínio

**Comment by fabiocerqueira** [comment]
eu tenho acesso, mas n tenho mais acesso ao gerenciamento do dominio. Pra validar o certificado tem que confirmar o ownership do dominio adicionado uma entrada no dns

**Comment by naanadr** [comment]
@fabiocerqueira você pode dar acesso ao email `tecnologia@python.org.br` e/ou podemos fazer um pair de 30 minutinhos para resolver isso. 

Se você puder fazer um pair, segue o [link](https://calendar.app.google/xhNHxMi6NxQGTsL77) para agendamento.
