### ISSUE TITLE
Transição de gestão: 2022/2023 -> 2024/2025

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#505]
Olá! Criando essa issue para registrarmos o processo de transição entre a atual e futura gestão da APyB.

Para cada tarefa feita, por favor indique se ela está documentada ou não no site https://apyb.python.org.br.

---

- [x] #509
- [x] #511
- [x] https://github.com/apyb/tarefas/issues/507

**Permissões**
- [x] #512
- [x] #510
- [x] Criar time `Diretoria 2022-2023` na organização APyB e adicionar a direção vigente
- [x] Adicionar nova diretoria nos times [pythonbrasil/apyb](https://github.com/orgs/pythonbrasil/teams/apyb) e [apyb](https://github.com/orgs/apyb/teams/diretoria)
- [x] Adicionar nova diretoria como `owners` das organizações [pythonbrasil](https://github.com/orgs/pythonbrasil/people?query=role%3Aowner) e [apyb](https://github.com/orgs/apyb/people?query=role%3Aowner)
- [x] Remover gestão anterior dos times [pythonbrasil/apyb](https://github.com/orgs/pythonbrasil/teams/apyb) e [apyb](https://github.com/orgs/apyb/teams/diretoria) (fazer apenas após a nova diretoria assumir a APyB)
- [x] Remover gestão como `owners` das organizações [pythonbrasil](https://github.com/orgs/pythonbrasil/people?query=role%3Aowner) e [apyb](https://github.com/orgs/apyb/people?query=role%3Aowner) (fazer apenas após a nova diretoria assumir a APyB)

**Comment by rougeth** [comment]
Grupo criado no Telegram com a presença da atual diretoria e futura gestão. Não documentado.

**Comment by naanadr** [comment]
@rougeth essa URL https://associacao.python.org.br/ deveria ser redirecionada para https://apyb.python.org.br/ ?

**Comment by rougeth** [comment]
> @rougeth essa URL https://associacao.python.org.br/ deveria ser redirecionada para https://apyb.python.org.br/ ?

Não, são sites diferentes mesmo. `associados.` é basicamente o sistema de pagamentos da APyB e onde controlamos quem é associado, e quem não é.

Já o `apyb.`, é a documentação de qualquer coisa relacionada a APyB. Começamos esse ano, o mais relevante é o manual de como a comunidade pode usar a APyB como infraestrutura para seus eventos.

Seria ótimo integrá-los, mas decidimos não focar nisso porque achamos o conteúdo mais importante no momento.

**Comment by rougeth** [comment]
@cecivieira @anicelysantos @naanadr enviei os convites para vocês participarem das orgs pythonbrasil e apyb aqui no Github. Marca com um 👍 quando vocês aceitarem pfv.

**Comment by cecivieira** [comment]
@rougeth os emails chegaram, mas nenhum com o botão para aceitar. As mensagens foram puramente informativas para mim.

**Comment by rougeth** [comment]
Ceci, você tem que entrar no GitHub e nas notificações deve aparecer um botão para aceitar ou ir para a página certa.

**Comment by cecivieira** [comment]
Ontem aceitei @rougeth . Encontrei o email com o botão de aceite da
organização "Apyb", depois que comentei aqui.
