### ISSUE TITLE
Atualizar cartões de créditos

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#507]
- [x] Heroku
- [x] Cloudflare
- [x] Flickr
- [x] AWS

**Comment by rougeth** [comment]
@cecivieira 
- Pagamos Heroku e AWS mensalmente.
- Cloudflare usei o cartão apenas para criar a conta.
- Pagamos a conta do Flickr para dois anos, e acho que precisaremos renovar em 2024. Existe um tipo de conta para ONGs que só descobri depois (vale a pena, plano normal é caro).

**Comment by cecivieira** [comment]
@rougeth não tem a senha do Flickr no KeePassXC.

Outras coisa, a AWS tá com pagamentos em atraso, mas quando vou para a área de contas aparece uma mensagem informando que o registro não foi finalizado. Como é feito o pagamento? Através de compra de crédito ou insercação de dados de um cartão de crédito?

Realizei a troca do cartão nas demais contas listadas nesta issue.

**Comment by cecivieira** [comment]
![image](https://github.com/apyb/tarefas/assets/30605862/06812acc-e86b-464c-bd17-e9d4e4078a21)

**Comment by rougeth** [comment]
> Como é feito o pagamento? Através de compra de crédito ou insercação de dados de um cartão de crédito?

Dados do cartão de crédito. Acho que a cobrança nos últimos são por conta do vídeos da pybr2024, geralmente não tem custo.

Vou pingar vc sobre esse "Complete sign-up".

**Comment by cecivieira** [comment]
Atualizei o cartão na AWS,mas a senha do Flickr ainda não aparece no cofre pra mim.
Não vi nenhum commit no cofre com ela : https://github.com/apyb/cofre/commits/main/
