### ISSUE TITLE
Criar template de issue para reuniões da diretoria

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#51]
Seria de grande valor se nossas atas de reuniões seguissem um padrão, e como estamos utilizando issues para registrar tais atas, acredito que um template de issue ajudaria bastante. Dito isso, segue uma sugestão de template:

```
# Reunião Diretoria

## Sobre
**Data**: dd/mm/YYYY
**Assunto**: Alinhamento quinzenal
**Participantes**:
- Nome Sobrenome @github 

## Pautas
- Tópico

## Ata

### Tópico

**Issue:** #<número-da-issue>
<descrição>
```

Outras sugestões são sempre bem-vindas!

**Comment by muriloviana** [comment]
Sugestão da @anadulce durante nossa última reunião, deixar a data no título da ata. Logo o template ficaria assim:

```
# Reunião Diretoria - dd/mm/YYYY

## Sobre
**Assunto**: Alinhamento quinzenal
**Participantes**:
- Nome Sobrenome @github 

## Pautas
- Tópico

## Ata

### Tópico

**Issue:** #<número-da-issue>
<descrição>
```

**Comment by rougeth** [comment]
PR com o template acima: https://github.com/apyb/tarefas/pull/58
