### ISSUE TITLE
Python Sudeste 2024 - email e domínio

### ISSUE THREAD

**Issue by anadulce** [apyb/tarefas#516]
A Python sudeste ficou desativada por quatro anos, e por isso perdemos o domínio que costumava ser utilizado, e o e-mail também.
Como são longos anos sem utilização, pretendíamos criar novos, sem necessariamente seguir o padrão anterior, de acordo com o que for melhor para a gerência da APyB.
Pensamos que seria um bom momento para seguir alguma padronização :)
Domínio anterior:
http://pythonsudeste.org/ 
E-mail anterior:
eventos@pythonsudeste.org

**Comment by naanadr** [comment]
@anadulce você sabe quem comprou esse dominio ? Pq se for alguém conhecido, podemos transferir para a APyB.

E sobre o e-mail, posso criar um `sudeste@python.org.br` .

**Comment by naanadr** [comment]
O e-mail `sudeste@python.org.br` já tinha sido criado pela gestão anterior, o domínio no entanto ainda continua em aberto.

**Comment by naanadr** [comment]
@anadulce vocês ainda tem interesse em passar o dominio do site?

**Comment by anadulce** [comment]
Nope, estamos usando o domínio que o Rougeth criou e já tá resolvendo o problema

**Comment by naanadr** [comment]
Ok, então estou fechando a issue. Qualquer coisa só falar :)
