### ISSUE TITLE
Reunião Diretoria - 17 de janeiro, 2024

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#521]
# Reunião Diretoria - 17/01/2024

## Sobre
- **Assunto**: Onboarding
- **Participantes**:
  - Ana Cecília Vieira - @cecivieira
  - Ana Dulce Padovan - @anadulce
  - Maria Fernanda Souza - @naanadr
  - Marco Rougeth - @rougeth
  - Anicely Santos - @anicelysantos

## Pautas
- Onboarding
- Comunicação (assíncrona interna e externa (responder a e-mails))
- Utilização de emails,
- Organização do Driver,
- AWS,
- Email de convite para evento Python
- Fernanda tem outras dúvidas, mas são mais relacionadas a diretoria de tecnologia e ela irá tirar diretamente com o Rougeth.

## Ata

- Abrir issues:
    - [ ] #522
        - Investigar o período que o GitHub leva para arquivar uma Action
    - [ ] #523
    - [ ] #526
    - [ ] #525
    - [ ] #524
- [Ler Manuais e Assistir vídeos](https://drive.google.com/drive/u/0/folders/0B_CQOAVUY5bRZC0wLXlyRTJnZjQ?resourcekey=0-vVGF7hbDK0lsuD1GK2pMUw) sobre Financeiro 
   - @cecivieira: voltar nesse assunto na próxima reunião, pós realização dessa atividade
- @anicelysantos vai pesquisar se associações podem emitir nota fiscal no site da RF
    - Código utilizado para emitir a NF: 246
- @anadulce vai confirmar se a Ata pode ser enviada para qualquer agencia do BB

### Tópico

**Issue:** #<número-da-issue>
<Discussão>

**Comment by naanadr** [comment]
Tópicos que eu gostaria de abordar:
- Utilização de emails,
- Organização do Driver,
- AWS,
- Email de convite para evento Python 

Outras dúvidas que eu tenho é mais relacionadas a diretoria de tecnologia e irei tirar diretamente com o Rougeth.

**Comment by naanadr** [comment]
Aberta as issues. e ata atualizada.
