### ISSUE TITLE
Solicitação de Pagamento: pybr2024 - Pagamento de Aluguel do salão para Nove Organizacao de Eventos LTDA

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#529]
#### Solicitação de Pagamento
- Evento: pybr2024
- Descrição:  Aluguel do salão para Nove Organizacao de Eventos LTDA
- Valor:  R$ 10880,00
- Demais dados enviados por e-mail (apyb-condir@)

**Comment by biancarosa** [comment]
Imagino que esteja fechado esse ticket :)

**Comment by cecivieira** [comment]
Pagamento realizado
https://drive.google.com/file/d/1u75XD6GeYVNTaVU0kURZ3gR3i06eZkT-/view?usp=drive_link
