### ISSUE TITLE
Atualizar token utilizado pelo Ultradox

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#532]
Remover o token do GitHub da diretória anterior que está sendo utilizada pelo Ultradox para disparar as Actions aqui do repositório.

**Comment by naanadr** [comment]
Atualizei o ultradox com o token criado no usuário @apyb-bot , dessa forma, independente da diretória o workflow executará 🙏🏼

**Comment by rougeth** [comment]
Chegou a testar? Você pode preencher um dos formulários que tem essa automação para confirmar que ta tudo certinho.

**Comment by naanadr** [comment]
> Chegou a testar? Você pode preencher um dos formulários que tem essa automação para confirmar que ta tudo certinho.

cheguei a testar sim @rougeth 

![image](https://github.com/apyb/tarefas/assets/21251472/889fa311-002f-4d63-b0e9-69d011190b47)
https://github.com/apyb/tarefas/actions
