### ISSUE TITLE
Nota Fiscal: PyNE2024 - Nota Fiscal para EVOLUX SISTEMAS

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#533]
#### Solicitação de Emissão de Nota Fiscal
- Evento: **PyNE2024**
- Descrição: **Nota Fiscal para EVOLUX SISTEMAS**
- Valor: **R$1.500,00**
- Demais dados enviados por e-mail (apyb-condir@).

#### Como emitir nota fiscal?
- [Como emitir uma nota fiscal de patrocinio (parte 1)](https://drive.google.com/drive/u/0/folders/0B_CQOAVUY5bRZC0wLXlyRTJnZjQ?resourcekey=0-vVGF7hbDK0lsuD1GK2pMUw)
- [Como emitir uma nota fiscal de patrocinio (parte 2)](https://drive.google.com/file/d/0B7AZ7Zt9Vp36Uk9mNG9lYzlDMUk/view?usp=sharing&resourcekey=0-tt-x0sW7i4WvcrPh6_QPKA)

**Comment by cecivieira** [comment]
Nota emitida e enviada hoje
