### ISSUE TITLE
Termo de Consentimento e Valores para divulgação das movimentações da APyB e PJ

### ISSUE THREAD

**Issue by muriloviana** [apyb/tarefas#55]
## Descrição

Durante a discussão sobre anonimização das movimentações financeiras da APyB (#1), surgiu a ideia de criar um **Termo de Valores da APyB** para que os patrocinadores e prestadores de serviços dos eventos estejam de acordo. Neste termo teríamos, a princípio, apenas o consentimento da publicação dos dados das movimentações entre a associação e o patrocinador em questão. No entanto, este mesmo termo pode ser útil futuramente para outros valores que acharmos pertinente ter.

**Comment by muriloviana** [comment]
O Bruno nos mostrou uma primeira versão do Termo de Consentimento/Valores, fizemos algumas observações e voltaremos a analisar novamente em breve.

Ficou pendente da diretoria, listar quais são os valores da associação que esperamos que as empresas as quais faremos contratos precisam contemplar. Exemplo: respeito a diversidade e transparência.

**Comment by tiidadavena** [comment]
Esse CdC do PyScript achei que pode ser um bom material complementar: https://github.com/pyscript/governance/blob/main/CODE-OF-CONDUCT.md

![image](https://user-images.githubusercontent.com/12106738/169139103-42104e02-8b9a-4329-99b7-7b3aab9f3da0.png)

**Comment by muriloviana** [comment]
Segue link do Termo: https://docs.google.com/document/d/1m3pewebkXuMskYya5x6TCytNQ4TqGdy0boFju148arM/edit
