### ISSUE TITLE
Compartilhar senha do eventbrite da Python Brasil no 1password

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#550]
Oi pessoal, precisando da senha do eventbrite da pybr no 1password 😉

**Comment by cecivieira** [comment]
@anadulce tu tem essa senha?
Não encontrei por aqui

**Comment by anadulce** [comment]
Tenho! Eu mando pra vocês assim daqui uma meia hora

**Comment by naanadr** [comment]
@biancarosa demanda resolvida?

**Comment by naanadr** [comment]
Credenciais adicionadas no 1password e senha alterada.
