### ISSUE TITLE
Domínio Python Norte 2024

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#553]
@naanadr trazendo um pedido da org da Python Norte aqui para o apyb:

> Opa, @rougeth. Tudo bem?
> A gente gostaria de usar o domínio https://2024.pythonnorte.org/ para o site da edição desse ano que atualmente está no domínio https://pynorte.github.io/pynorte2024-site/. Com quem a gente pode falar sobre isso?

https://github.com/PyNorte/pynorte2024-site/issues/2

---

Para APyB:
- [x] Configurar o subdomínio `2024.` e apontar para pynorte.github.io
- [ ] Configurar o domínio `pythonnorte.org` para redirecionar para o novo subdomínio

Para a org da Python Norte
- [ ] Configurar o domínio `2024.pythonnorte.org` no repositório do site (https://github.com/PyNorte/pynorte2024-site/settings/pages). Não esquecer de marcar a opção `Enforce HTTPS`.

**Comment by naanadr** [comment]
@MateusSantosMeuBem vocês conseguiram configurar o domínio no github?

**Comment by naanadr** [comment]
@rougeth seria para configurar o domínio `2024.pythonnorte.org` no repositório de 2023 ou do 2024?

**Comment by rougeth** [comment]
> @rougeth seria para configurar o domínio `2024.pythonnorte.org` no repositório de 2023 ou do 2024?

2024, ajustei o texto com o link do repositório certo.

**Comment by MateusSantosMeuBem** [comment]
> @MateusSantosMeuBem vocês conseguiram configurar o domínio no github? Porque quero saber se a url `2024.pythonnorte.org/` não está funcionando por causa disso, ou por outro motivo.

@naanadr, não, não. A gente só subiu a aplicação no GitHub pages e verificou o Enforce HTTPS (está ativado).

**Comment by naanadr** [comment]
> > @MateusSantosMeuBem vocês conseguiram configurar o domínio no github? Porque quero saber se a url `2024.pythonnorte.org/` não está funcionando por causa disso, ou por outro motivo.
> 
> @naanadr, não, não. A gente só subiu a aplicação no GitHub pages e verificou o Enforce HTTPS (está ativado).

ok, então não chegaram a configurar o dominio nas settings do github @MateusSantosMeuBem ? se não, poderia fazer isso por favor.

**Comment by MateusSantosMeuBem** [comment]
@gabrovskii, podes fazer isso? Com as minhas permissões, não achei alguma opção na [página de configuração das páginas](https://github.com/PyNorte/pynorte2024-site/settings/pages) com essas opções.

**Comment by gabrovskii** [comment]
@MateusSantosMeuBem domínio configurado.

Só um detalhe, parece que o link não está levando para home page, alguém saberia ajudar a descobrir o motivo?

![image](https://github.com/apyb/tarefas/assets/36344623/0b85c012-1e8c-4683-a588-ef30d338d355)

**Comment by luzfcb** [comment]
@gabrovskii verificou essa falha? https://github.com/PyNorte/pynorte2024-site/actions/runs/8251988331/job/22570417301

**Comment by naanadr** [comment]
A url https://2024.pythonnorte.org/ aparentemente está funcionando, o site de vocês que está quebrado 😞  E o redirect da url https://pythonnorte.org/ para https://2024.pythonnorte.org/ foi configurado (ele deve demorar um tempinho para estar 100%).

**Comment by MateusSantosMeuBem** [comment]
@luzfcb ESTÁ VIVO! Obrigado, pessoal!

**Comment by gabrovskii** [comment]
Obrigado pessoal!

**Comment by naanadr** [comment]
Pronto pessoal, o domínio https://2024.pythonnorte.org/ está funcionando, as urls https://pythonnorte.org/ https://www.pythonnorte.org/ redirecionam para a página nova.
