### ISSUE TITLE
Revisar o balanço financeiro

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#561]
- Atualizar o [site do financeiro](https://financeiro.python.org.br/) com os extratos faltantes 
  - [ ] Adicionar extratos no repositório [apyb/financeiro](https://github.com/apyb/financeiro)
  - [ ] Revisar o balanço presente no site com o dinheiro existente na conta do banco
- [ ] Adicionar extratos no Drive

**Comment by cecivieira** [comment]
Issue substituída por específicas mensais como #586
