### ISSUE TITLE
Uso do Pretalx para eventos

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#562]
https://github.com/apyb/comunidade/discussions/111

**Comment by naanadr** [comment]
Eu e a @tiidadavena estamos em um grupo do telegram onde as pessoas interessadas em desenvolver um MVP de um Pretalx mantido pela comunidade está se organizando. 

Deixamos claro que esse serviço não está nos planos da diretoria hospedar em uma infra interna nossa e nem ser mantido pela diretoria. Ficaram todos de acordo, e nós da diretoria estamos em contato com a comunidade a fim de tirar dúvidas sobre o uso da APyB e auxiliar pontualmente. 

O código do Pretalx será armazenado na organização [comunidade-python-br](https://github.com/comunidade-python-br) e será hospedado em uma conta da AWS que foi criada com essa finalidade. Do lado da APyB ficamos de criar um domínio chamado `talks.python.org.br` (Issue https://github.com/apyb/tarefas/issues/566) que será utilizado para acessar o Pretalx. 

Todas as decisões de arquitetura, gerenciamento de projeto e afins, estão sendo realizados pela comunidade. A organização da Python Sul 2024 e Python Brasil 2024 estão atuando ativamente para desbloquear o MVP, de forma que possam utilizar esse ano em seus respectivos eventos.
