### ISSUE TITLE
Validar uso do Stripe como alternativa para o site de associados

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#564]
Hoje temos o site de associados apenas para que as pessoas consigam assinar a associação, mas o site é mantido pela diretoria e tem um custo relativamente alto de hospedagem (#63), além de precisar de atualizações e desenvolvimento de novas features. 

A Stripe parece ser uma boa alternativa para substituir o site de associados, algumas features que chamaram a nossa atenção:
- É possível criar uma página de cadastro e permite que o usuário loge no sistema para acompanhar o status da assinatura,
- A assinatura é renovada automaticamente,
- Conseguiremos aceitar pagamento em outras moedas.

Issues relacionadas:
- [x] #678
- [x] Criar uma página de teste para validar a ferramenta
- [x] #679

Caso essa validação se mostre positiva, novas atividades serão realizadas, como:

- [ ] #683
- [x] #682
- [x] #680
- [x] #681
- [ ] Atualizar o site da apyb com um [novo tema](https://sphinx-themes.readthedocs.io/en/latest/) (caso seja necessário)

**Comment by naanadr** [comment]
Taxa do Stripe:



![Image](https://github.com/apyb/tarefas/assets/21251472/65989800-03d5-4655-a189-97a286d1dbeb)

**Comment by rougeth** [comment]
@naanadr alguns pontos e perguntas:

- Importante notar que o alto custo de hospedagem hoje se dá pela má gestão do provedor que usamos (Heroku), e não pela infraestrutura necessária para manter o site. A impressão que tenho é que o Heroku está em modo KTLO e que o Salesforce não tem planos a longo prazo para o serviço.
- Outra questão é que o site é muito simples, novas features seriam ótimas (consigo pensar em várias), porém não vejo nenhuma como essencial ao longo prazo. A última versão LTS do Django (4.2) terá suporte até 2026, e a próxima, 5.2 a ser lançada em 04/2025, terá suporte até 2028. Manter as bibliotecas atualizadas poderia ser um sprint organizado pela APyB e feito pela comunidade.
- Hoje qualquer pessoa consegue ver quem são as pessoas associadas a APyB. Isso ainda poderia ser feito usando a Stripe? Quais outras features do site perderíamos em caso de mudança?
- Como a APyB manteria o histórico de seus associados?
- Stripe trabalha com associações?
- Stripe aceita PIX apenas para empresas convidadas. Quantos associados usam PIX para pagar a anuidade?

**Comment by tiidadavena** [comment]
> @naanadr alguns pontos e perguntas:
> 
> * Importante notar que o alto custo de hospedagem hoje se dá pela má gestão do provedor que usamos (Heroku), e não pela infraestrutura necessária para manter o site. A impressão que tenho é que o Heroku está em modo KTLO e que o Salesforce não tem planos a longo prazo para o serviço.
> * Outra questão é que o site é muito simples, novas features seriam ótimas (consigo pensar em várias), porém não vejo nenhuma como essencial ao longo prazo. A última versão LTS do Django (4.2) terá suporte até 2026, e a próxima, 5.2 a ser lançada em 04/2025, terá suporte até 2028. Manter as bibliotecas atualizadas poderia ser um sprint organizado pela APyB e feito pela comunidade.
> * Hoje qualquer pessoa consegue ver quem são as pessoas associadas a APyB. Isso ainda poderia ser feito usando a Stripe? Quais outras features do site perderíamos em caso de mudança?
> * Como a APyB manteria o histórico de seus associados?
> * Stripe trabalha com associações?
> * Stripe aceita PIX apenas para empresas convidadas. Quantos associados usam PIX para pagar a anuidade?

Acredito que um levantamento rápido com a coumidade já fornceria uma visão inicial acerca do último questionamento.

Não entendi no que o Stripe poderia interferir na listagem dos usuários, já que esse processo é do backend.

Concordo 100% com a migração para outra ferramenta de hosting - sugiro fly.io ou render.com, e até o Netlify poderia fazer isso - e talvez migrar o DB para o [Supabase](https://supabase.com/).

**Comment by naanadr** [comment]
Olá @rougeth a Jules já trouxe alguns pontos, mas complementando:

> Importante notar que o alto custo de hospedagem hoje se dá pela má gestão do provedor que usamos (Heroku), e não pela infraestrutura necessária para manter o site. A impressão que tenho é que o Heroku está em modo KTLO e que o Salesforce não tem planos a longo prazo para o serviço.

Obrigada por ter deixado mais claro o que foi levantado brevemente na descrição da issue #63. Irei fazer a migração de provedor nessa outra issue, essa daqui eu criei apenas para validar se o Stripe seria viável como meio de pagamento, já que aceita cartões internacionais. 

> Outra questão é que o site é muito simples, novas features seriam ótimas (consigo pensar em várias), porém não vejo nenhuma como essencial ao longo prazo. A última versão LTS do Django (4.2) terá suporte até 2026, e a próxima, 5.2 a ser lançada em 04/2025, terá suporte até 2028. Manter as bibliotecas atualizadas poderia ser um sprint organizado pela APyB e feito pela comunidade.

Entendo o seu ponto. Mas atualmente estamos pensando em futuramente agregar tudo em um único site. Não tendo mais a wiki e o associados em locais diferentes. 

> Hoje qualquer pessoa consegue ver quem são as pessoas associadas a APyB. Isso ainda poderia ser feito usando a Stripe? Quais outras features do site perderíamos em caso de mudança?

Como Jules falou anteriormente, conseguimos pegar a lista de usuários pela API do Stripe e os admins conseguem exportar a lista de usuários ativos facilmente pelo dashboard da Stripe. Além disso, a diretoria atual não vê essa funcionalidade como prioritária, e no futuro caso seja realizado a migração, podemos disponibilizar uma página com mais detalhes de quantidade de usuários ativos e o nome deles. 

> Como a APyB manteria o histórico de seus associados?

Tas falando do banco postgres? Se sim, não iriamos fazer a migração dele para o Stripe. O que iriamos fazer, é mudar o link de pagamento no site do associados, para as pessoas começarem a pagar a membresia por lá e depois quando tiverem todos cadastrados na Stripe, ai sim iriamos matar o nosso banco postgres. Por isso, a migração de servidor irá acontecer de toda forma.

Se não era isso que tu estava falando, poderia explicar melhor essa pergunta? 😄 

> Stripe trabalha com associações?

Aparentemente eles oferecem desconto das taxas para organizações sem fim lucrativos ([aqui](https://support.stripe.com/questions/fee-discount-for-nonprofit-organizations?locale=pt-BR#:~:text=A%20Stripe%20oferece%20processamento%20sem,n%C3%A3o%20abrange%20produtos%20ou%20ingressos).)

> Stripe aceita PIX apenas para empresas convidadas. Quantos associados usam PIX para pagar a anuidade?

Sim verdade, mas aceitam boleto. Estamos tentando levantar esses dados com exatidão, mas aparentemente desde o começo do ano tivemos 12 pessoas pagando em pix a anuidade.

**Comment by rougeth** [comment]
Testei a página de teste, seria ótimo ter a forma de pagamento na própria wiki! Algumas ideias que surgiram (ignora se vocês já pensaram/discutiram):

- Após a confirmação de inscrição, os webhooks da stripe poderiam acionar uma action no github responsável por adicionar a mudança num .csv/.json/db que a APyB mantém (coisa simples, atualiza um arquivo texto no S3 por exemplo). Dessa forma seria possível manter histórico que já temos hoje.
- Também poderíamos ter outra automação que atualiza uma página na wiki, adicionando a nova pessoa associada. Hoje essa informação é pública, seria interessante manter.

Respondendo aos itens anteriores:

> O que pensamos em fazer, seria mudar o link de pagamento no site do associados, para as pessoas começarem a pagar a membresia por lá e depois quando tiverem todos cadastrados na Stripe, ai talvez fossemos matar o banco postgres.

Acho que a migração vai ser "fácil". Como não temos pagamento recorrente, na hora de renovar, é só a APyB enviar o link do novo provedor.

**Comment by naanadr** [comment]
> Após a confirmação de inscrição, os webhooks da stripe poderiam acionar uma action no github responsável por adicionar a mudança num .csv/.json/db que a APyB mantém (coisa simples, atualiza um arquivo texto no S3 por exemplo). Dessa forma seria possível manter histórico que já temos hoje.

Eu tinha pensado em algo parecido, mas não tinha parado para olhar com calma como que funciona o webhook. O que eu tinha visto era que dava para exportar a lista de assinantes pela UI do Stripe, e até ter esse update automático, conseguiríamos validar quem é assinante e quem não é. Depois de fazer a migração do site do associados do heroku para outro lugar, talvez consigamos continuar mantendo um db. 

> Também poderíamos ter outra automação que atualiza uma página na wiki, adicionando a nova pessoa associada. Hoje essa informação é pública, seria interessante manter.

Essa parte de exportar a lista de associados, está bem no backlog e não enxergamos como uma feature prioritária. Mas a ideia de utilizar o github action + o webhook parece interessante também. O que tínhamos pensado em fazer, era disponibilizar uma página com o Streamlit, mostrando mais dados como "quantidade de assinantes ativos por ano" e bla bla bla. 

> Acho que a migração vai ser "fácil". Como não temos pagamento recorrente, na hora de renovar, é só a APyB enviar o link do novo provedor.

Também estou com essa esperança 🙏

**Comment by naanadr** [comment]
Atualizei a descrição da issue com as subtarefas que estarei executando.
