### ISSUE TITLE
Apontamento do registro de DNS para o pretalx da Python Brasil

### ISSUE THREAD

**Issue by flaviocpontes** [apyb/tarefas#566]
Criei a hosted Zone na AWS e agora é necessário que seja feito o apontamento do name server para a nova Hosted Zone.

Domínio: talks.python.org.br
Os name servers são:
ns-1596.awsdns-07.co.uk
ns-435.awsdns-54.com
ns-1436.awsdns-51.org
ns-788.awsdns-34.net

**Comment by naanadr** [comment]
@flaviocpontes eu preciso apenas do IP da aplicação para que eu possa criar um A ou um CNAME, como fizemos anteriormente com outros subdomínios dentro do `python.org.br`

![image](https://github.com/apyb/tarefas/assets/21251472/a59a7eed-87b5-42d9-83a3-134362e581fb)

**Comment by flaviocpontes** [comment]
@naanadr Tem que ser uma entrada NS porque o IP da aplicação é dinâmico e eu não tenho um domínio pra criar um CNAME.
Eu criei uma hosted zone na AWS para talks.python.org.br. Só preciso do apontamento pra levantar o pretalx

**Comment by LanusseMorais** [comment]
@naanadr vamos precisar apontar o talks.python.org.br para esse ip aqui 137.184.37.101. Também vamos precisar de acesso de alguma forma para o e-mail noreply@python.org.br, para disparar os e-mails

**Comment by naanadr** [comment]
IP adicionado no registro TXT do `python.org.br`, servidor SMTP configurado na conta do google da APyB para habilitar envio de e-mail pelo `noreply`. 

Testes foram realizados junto com a Lanusse hoje, e deu tudo certo.
