### ISSUE TITLE
Reunião Diretoria - 17 de abril, 2024

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#570]
# Reunião Diretoria - 24/04/2024

## Sobre
- **Assunto**: Alinhamento quinzenal
- **Participantes**:
  - Maria Fernanda Souza @naanadr
  - Anicely Santos @anicelysantos
  - Ana Cecília Vieira @cecivieira

## Pautas
- Atualizar o [site do financeiro](https://github.com/apyb/financeiro/tree/main) com os extratos dos últimos 6 meses
- Atividades relacionadas a transição
- Grupo de Trabalho do Pretalx
- Validar uso do Stripe como alternativa para o site de associados #564
- Report dos apoios dos eventos que usam a infraestrutura da APyB
- Verificar se APyB pode usar a Lei Rouanet para liberação de patrocínios 
- [Reembolsos pendentes](https://github.com/apyb/tarefas/issues?q=is%3Aissue+is%3Aopen+Solicita%C3%A7%C3%A3o+de+reembolso+)
- `apyb-bot` sem funcionar corretamente
- Abrir de forma automática issue relacionada ao balanço financeiro 
- Documentação sobre o onboarding antes que seja tarde de mais (https://github.com/apyb/tarefas/issues/540)

#### Atividades pendentes da transição
**Issue:** #507 #505
- Cartão de crédito virtual cadastrado pela diretoria de financeiro precisou ser cancelado
- Diretoria realizou a mudança do cartão de crédito nos serviços
- Todas as atividades pendentes relacionadas a transição foram resolvidas

#### Documentação de processos
**Issue:** #526 https://github.com/apyb/comunidade/discussions/111
- @anicelysantos vai confirmar se as seguintes informações estão na docs
  - Prazo de solicitação de reembolso e prazo de pagamentos - prazo de até 15 dias depois do evento e previsão de recebimento em até 60 dias (prazos a confirmar)
  - Tempo máximo em dias úteis que a diretória de financeiro tem para responder solicitações
- Adicionar na documentação da apyb sobre o uso da infraestrutura e como a apyb pode auxiliar um projeto desenvolvido pela comunidade. Utilizar como base o que está sendo feito no Pretalx

#### Demandas do financeiro
**Issue:** #561 #507 #565 #541
- Demandas atrasadas do financeiro serão realizadas na segunda quinzena de maio. As demandas atrasadas são:
  - Balanço financeiro
  - Verificar se a diretoria anterior deixou algum pagamento pendente
- A diretora de tecnologia adicionou um workflow que abre de forma automática e mensalmente a issue relacionada ao balanço financeiro
- Membras da diretoria estão fazendo um multirão assincrono para fechar as issues do financeiro que estão abertas
- A presidente está tentando validar os dados para acessar a conta do PagBank, caso não consiga, ela irá acionar a gestão anterior
- A diretoria esqueceu de escrever a devolutiva sobre o uso da Lei Rouanet, porque já conversamos sobre esse ponto na reunião anterior. @anicelysantos ficará responsável por dar um retorno formal.

#### Indexar a Homepage da APyB
**Issue:** #563
- Parece ter se resolvido após a configuração dos sites da APyB no Dashboard do Google
- Evidências serão adicionadas a issue

#### Grupo de Trabalho do Pretalx
**Issue:** https://github.com/apyb/comunidade/discussions/111 #566 #575 
- O pretalx agora está disponível na url: https://talks.python.org.br/
- A diretoria concordou que podemos ajudar na divulgação do GT e da ferramenta

#### Eventos que utilizam a infraestrutura da APyB
- PSF enviou o patrocinio da Python Brasil e da Python Sul na mesma remessa. Isso acabou gerando confusão e demora no retorno de confirmação para a organização da PySul

#### O bot da apyb não estava funcionando e mensagens novas no discussion não estavam sendo enviadas
**Issue:** https://github.com/apyb/apyb-bot/issues/13
- Boletim informativo de março tinha sido postado no discussion, mas não tinha sido replicado para a lista de e-mail. Depois que o a lib do bot foi corrijida, o boletim foi compartilhado com a lista de e-mail

#### Avançar na discussão sobre assinatura de membresia
**Issue:** #63 #564

- Foi levantado uma versão de teste do site da apyb para experimentação do stripe: https://apyb.python.org.br/pr-preview/pr-21/associados/associe-se/
- Resultados dos testes estão documentados na issue ([comentário](https://github.com/apyb/tarefas/issues/564#issuecomment-2065570689))
- A diretoria seguirá com a implementação do Stripe como forma de pagamento e sistema de assinatura 
- O site dos associados será migrado de servidor e também terá link de pagamento atualizado
- Após a migração, gardaremos um backup do banco de dados atual para eventuais consultas de histórico.

**Comment by tiidadavena** [comment]
#566

**Comment by tiidadavena** [comment]
#564

**Comment by tiidadavena** [comment]
#541

**Comment by tiidadavena** [comment]
- Report dos apoios dos eventos que usam a infraestrutura da APyB

**Comment by tiidadavena** [comment]
[Reembolsos pendentes](https://github.com/apyb/tarefas/issues?q=is%3Aissue+is%3Aopen+reembolso)

**Comment by tiidadavena** [comment]
#569

**Comment by naanadr** [comment]
https://github.com/apyb/apyb-bot/issues/13

**Comment by naanadr** [comment]
https://github.com/apyb/tarefas/issues/565
