### ISSUE TITLE
Problemas com o domínio plone.org.br

### ISSUE THREAD

**Issue by ericof** [apyb/tarefas#577]
O domínio plone.org.br, que é registrado pela APyB, não está mais apontando para os servidores de DNS da Cloudflare, conforme demonstrado abaixo:
```
$ dig plone.org.br

; <<>> DiG 9.10.6 <<>> plone.org.br
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11171
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;plone.org.br.			IN	A

;; AUTHORITY SECTION:
org.br.			884	IN	SOA	a.dns.br. hostmaster.registro.br. 2024116292 1800 900 604800 900

;; Query time: 20 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Apr 25 09:14:01 -03 2024
;; MSG SIZE  rcvd: 103
```

Alguém com acesso a conta da APyB no registro.br poderia, por favor, dar uma olhada no que está acontencendo?

**Comment by naanadr** [comment]
O domínio tinha vencido e os lembretes de pagamento estavam sendo direcionados para um e-mail que não utilizamos mais.

![Image](https://github.com/apyb/tarefas/assets/21251472/69e5a61c-d980-4c68-a0a0-5f0aa8ae4f99)


O pagamento foi realizado e o domínio reestabelecido.
