### ISSUE TITLE
Reunião Diretoria - 08 de maio, 2024

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#588]
# Reunião Diretoria - 08/05/2024

## Sobre
- **Assunto**: Alinhamento quinzenal
- **Participantes**:
  - Ana Cecília Vieira @cecivieira
  - Anicely Santos @anicelysantos
  - Juliana @tiidadavena

## Pautas
- Novos prazos de reembolso
- Atividades pendentes da comunicação
- Atividades da diretoria
- Retorno sobre Lei Ruanet

## Ata
Issue relacionada: https://github.com/apyb/tarefas/issues/526 
- Novos prazos de reembolso: Todos os reembolsos ainda não solicitados, de gastos realizados entre Jun. 23/abr. 2024 devem ser cadastrados no Ultradox (link) até 31 de maio. A partir desta data passa vigorar os seguintes prazos:
Todos os reembolsos devem ser solicitados até 30 dias após gasto realizado.
Sendo o período máximo para solicitação de pagamento ou reembolso 60 dias após a realização do evento. 

Issue relacionada: https://github.com/apyb/tarefas/issues/586
- Os balanços de 2023 estão em andamento. Já foi fechado o mês de setembro, com duas pendências. Até domingo (12/05) o ano de 2023 será concluído. Rougeth está apoiando na tarefa.

- A planilha financeira será descontinuada pela duplicação de trabalho e todo conteúdo relacionado ao finaceiro será centralizado no site de [transparência financeira](https://financeiro.python.org.br/apyb/balance_sheet/).

Issue relacionada: https://github.com/apyb/tarefas/issues/541
- Não vamos seguir com a discussão sobre a Lei Rouanet por haver muitas burocracias que envolvem receber dinheiro de organizações federais. Não temos braços suficientes nesta gestão. 

 Issue relacionada: https://github.com/apyb/tarefas/issues/575
- Criaremos uma seção no site explicando sobre a importância de existir grupos de trabalho na comunidade, mas explicitando que não haverá comprometimento financeiro nem de manutenção técnica nos produtos gerados.
 
 Issue relacionada: #559 #575 #558 #557
- A comunicação vai adquirir o Buffer neste mês de maio. Após isso, todas as pendências de postagem da comunicação serão sanadas.

- Sobre a situação do Rio Grande do Sul vamos apoiar divulgando iniciativas que já estão fazendo um trabalho de apoio a região.

**Comment by naanadr** [comment]
Sugestão, adicionar o novo prazo de solicitação de reembolso no manual.

Issue relacionada: https://github.com/apyb/tarefas/issues/526

**Comment by tiidadavena** [comment]
Divulgação de ajuda e de pontos de arrecadação para ajudar as vítimas das enchentes no RS
