### ISSUE TITLE
Conserto - Fluxo Ultradox de entrada de Receita

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#596]
o fluxo do Ultradox referente a solicitaćão de nota fiscal, está funcionando apenas até o e-mail onde informa sobre a nota fiscal emitida.

Nesta mensagem NÃO contém link onde eu possa associar um comprovante de depósito comprovando o recebimento deste valor.

Este é o e-mail recebido com a nota fiscal emitida (ver primeiro comentário).

Pelo que entendi na nossa conversa async da semana passada, essa e-mail informando sobre a emissão da nota deveria conter um link de uso exclusivo da Diretoria para que houvesse o enlace entre nota fiscal e depósito bancário recebido.

Isso não está acontecendo.

Desta maneira, subentende-se que a movimentaćão de notas fiscais entre a pasta "A Receber" e "Receitas" também não está funcionando.

-----
Se for possível, adiciona nesse fluxo o envio de e-mail para a solicitante, informando quando o comprovante de depósito for associado a nota fiscal.

**Comment by cecivieira** [comment]
![image](https://github.com/apyb/tarefas/assets/30605862/bf716183-7389-4c57-86ce-b87de18347cd)

**Comment by naanadr** [comment]
O fluxo não está quebrado, essa funcionalidade que não foi implementada 🤣 

Mesma coisa é com o fluxo de solicitação de invoice 😞 

Estou fazendo as alterações em um fluxo de teste aqui, e essa semana deve chegar alguns e-mails de validação no email.

**Comment by naanadr** [comment]
Sobre o fluxo de solicitação de Nota Fiscal:

* O e-mail agora é enviado pelo NoReply: ![Image](https://github.com/apyb/tarefas/assets/21251472/92706af1-d41e-47c6-8106-f02c20699ccb)
* No primeiro e-mail enviado, contém os links do ultradox que deverão ser utilizados:  ![Image](https://github.com/apyb/tarefas/assets/21251472/166796ae-7bc2-4f6e-b4b4-8b17445aba3e)
   * O primeiro link, deverá ser utilizado para anexar a NF gerada
   * O segundo link, deverá ser utilizado para anexar um comprovante do recebimento do dinheiro na conta do BB 
* O arquivo da NF é salvo na pasta `A Receber`: ![Image](https://github.com/apyb/tarefas/assets/21251472/9e427d30-f72d-499c-a5a3-9272ff5101c5)
* Depois que for confirmado o recebimento do dinheiro:
    * A NF é removida da pasta `A Receber`,
    * A NF é agregada ao comprovante de deposito,
    * Esse novo PDF é salvo na pasta `Receita`: ![Image](https://github.com/apyb/tarefas/assets/21251472/23825200-9b4f-4a60-92c9-e49f33660269)

**Comment by naanadr** [comment]
@cecivieira fluxo novo em produção. Agora as urls estão apontando para eles. 

Por favor, caso as novas solicitações estejam sem os links referenciados, me avise para que eu possa corrigir o quanto antes 🤗 ❤️
