### ISSUE TITLE
Reunião Diretoria - 03 de Julho, 2024

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#658]
# Reunião Diretoria - 03/07/2024

## Sobre
- **Assunto**: Alinhamento quinzenal
- **Participantes**:
  - Anicely Santos @anicelysantos
  - Juliana (Jules) Barros Lima @tiidadavena 

## Pautas

* Criação de um protocolo de evento, pensando em não repetir o que aconteceu no CODA Amazonia 2024
* Atualizar termo de compromisso de Big Kahuna, para garantir que poderão ser responsabilizados caso os manuais não sejam cumpridos
* Criação de um protocolo de resposta à quebra do CDC - [Protocolos de emergência](https://docs.google.com/document/d/16S_JAE5s0yBH3oux6wFwtmn8oEHGjDHrav60tUfNEoI/edit#heading=h.jr81gn14xomh)
* Termos obrigatórios no formulário de inscrição da Python Brasil, como: alergias a medicamentos e contatos de emergência 
    * Foi mencionada a possibilidade de reabrir as inscrições e informar que a inscrição do evento só será confirmada mediante envio dos dados de emergência
* Gravação das palestras da PyBr2023
    * Recebemos o HD com o material bruto das gravações
    * Temos o material também no S3
    * Organização está dispersa e talvez nós precisemos fazer a separação do material bruto das gravações
    * @rougeth você tinha mencionado que tinha um script para fazer recorte dos vídeos das palestra -  [scripting para edição dos vídeos](https://github.com/rougeth/pybrtools)

## Ata

- A Consultoria Jurídica finalizou o suporte em relação à matéria do The Intercept.

- Termos obrigatórios no formulário de inscrição da Python Brasil, como: alergias a medicamentos e contatos de emergência:@anicelysantos disse que para entrarmos em contato com os Big Kahuna das Norte, Nordeste, Cerrado, Sudeste e Sul
e PyBR. Levar a demanda para o grupo da Diretoria para saber se agendamos uma reunião com todes ou se criamos um grupo no Telegram com essas lideranças.

- **[PERGUNTA]** Vamos continuar com a rotação de pessoas que fazem o boletim ou apenas uma pessoa da diretoria faz os boletins? @tiidadavena vai assumir essa demanda e o texto de cada boletim será enviado para revisão conjunta com as outras Diretoras.

### Tópico

- **Issue:** #616 : Cancelar essa atividade, porque temos o #665 para ser feito 
- **Issue:**  #596 : Fluxo de solicitação de NF e Invoice estão atualizados (adicionar no #665)
- **Issues:** #84 e #31 : acabaram sendo realizadas - (adicionar no #665)
**Issue:** #564 
  - A Diretora de Tecnologia irá retomar essa task semana que vem
- **Issue:** #677 
  - Precisamos de ajuda para realizar essa atividade

**Comment by naanadr** [comment]
Mais alguns tópicos para serem falados:

Consultoria jurídica:
- Criação de um protocolo de evento, pensando em não repetir o que aconteceu no CODA Amazonia 
- Atualizar termo de compromisso de Big Kahuna, para garantir que poderão ser responsabilizados caso os manuais não sejam cumpridos
- Criação de um protocolo de resposta à quebra do CDC
- Termos obrigatórios no formulário de inscrição, como: alergias a medicamentos e contato de emergência

**Comment by rougeth** [comment]
> Criação de um protocolo de resposta à quebra do CDC

Em 2020, criamos um protocolo para equipe de resposta. Versões desses documentos foram usados nas edições seguintes:
- [Protocolo da equipe para resposta aos incidentes que infringem o Código de Conduta](https://docs.google.com/document/d/16S_JAE5s0yBH3oux6wFwtmn8oEHGjDHrav60tUfNEoI/edit?usp=sharing)
- [Protocolo do participante para denunciar incidentes que infringem o Código de Conduta](https://docs.google.com/document/d/1Mc9RItU7aFU6KMeVFsVxEGmJNeSXDdUaqudhPH7P018/edit)

**Comment by naanadr** [comment]
Mais um tópico para a ata

- Gravação das palestras da PyBr2023
  - Recebemos o HD com o material bruto das gravações 
  - Temos o material também no S3
  - Organização está dispersa e talvez nós precisemos fazer a separação do material bruto das gravações 
  - @rougeth você tinha mencionado que tinha um script para fazer recorte dos vídeos das palestras. Seria o repositório [rougeth/pybrtools](https://github.com/rougeth/pybrtools) ?

**Comment by naanadr** [comment]
Issues finalizadas por mim ou que eu irei trabalhar:
- #616 
  - Cancelar essa atividade, porque temos o #665 para ser feito 
  - **[PERGUNTA]** Vamos continuar com a rotação de pessoas que fazem o boletim ou apenas uma pessoa da diretoria faz os boletins?
- #596 
  - Fluxo de solicitação de NF e Invoice estão atualizados
  - Acho que as issues #84 e #31 acabaram sendo realizadas, mesmo não sendo a minha intenção 🤔 
- #564 
  - Irei voltar a essa atividade na próxima quinzena

**Comment by rougeth** [comment]
> @rougeth você tinha mencionado que tinha um script para fazer recorte dos vídeos das palestras. Seria o repositório [rougeth/pybrtools](https://github.com/rougeth/pybrtools)?

Sim, esse mesmo.

**Comment by cecivieira** [comment]
#696
