### ISSUE TITLE
Pedir um segundo orçamento para o Klayton/Tai considerado os itens no briefing

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#66]
Briefing: https://hackmd.io/1T-PblbOTEKvIx8d1LSWYg

**Comment by tiidadavena** [comment]
#38

**Comment by tiidadavena** [comment]
Proposta de investimento recebida em 01/ago, após avaliação pela diretoria que resultou nos desdobramentos na issue #119; foi decidido que seguiremos a busca pelos orçamentos com outros profissionais.

Assim sendo, os materiais a serem usados serão os já existentes e os novos (caso venham a surgir) deverão ser usados com base nestes.
