### ISSUE TITLE
Entrar em contato com Mário para checar acesso a páginda a APyB no Facebook

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#67]
Página no Facebook: https://pt-br.facebook.com/associacaopythonbr/

**Comment by tiidadavena** [comment]
@rougeth o ponto de contato seria o Mário Sérgio?

**Comment by rougeth** [comment]
Isso Ju.

**Comment by tiidadavena** [comment]
Atualizações: Mário também afirmou que não conseguiu encontrar as credenciais para ter acesso ao Facebook. A estratégia seria semelhante a criar um novo email para as contas no Meta (Instagram e Facebook). Uma outra opção seria usar o email do Twitter.

**Comment by tiidadavena** [comment]
Pelo que vi o email usado pelo Instagram da PyBR é pessoal. (Apesar do LastPass só compartilha-se o login e a senha de acesso).

**Comment by tiidadavena** [comment]
O que podemos fazer no momento é abrir um chamado com a equipe do Meta para solicitar recuperação da conta para termos, pelo menos, acesso ao backup de mídias e outros dados.

**Comment by tiidadavena** [comment]
Como esta issue estava diretamente ligada à #111 , esta issue também foi solucionada.
