### ISSUE TITLE
Corrigir fluxo do ultradox

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#671]
Após concluir a transação bancária para realização do reembolso solicitado na #667 , fui adicionar o comprovante de pagamento utilizando o link https://www.ultradox.com/app/1Npio95ZKLeaRC2FHXu-xp8GqHoGvRvl9?rak=ag9zfmZsb3JleXNvZnR1ZHhyEgsSBVRpbWVyGICAiPforq8JDA (disponibilizado no e-mail). No entanto, a página apresenta a seguinte mensagem de erro:
![image](https://github.com/apyb/tarefas/assets/30605862/79636574-5ec2-4764-a720-9a01106d591a)

**Comment by cecivieira** [comment]
Abaixo o comprovante de reembolso que deve ser anexado ao arquivo de solicitação para que seja provado seu pagamento.

[Comprovantes BB (19).pdf](https://github.com/user-attachments/files/16098803/Comprovantes.BB.19.pdf)

**Comment by naanadr** [comment]
@cecivieira os fluxos tinham sido desabilitados, habilitei novamente eles. Agora esses links intermediários voltaram a funcionar. 

Quando você terminar de utilizar o fluxo antigo, me avisa para que eu volte a desativar eles.
