### ISSUE TITLE
Comunicar aos associados sobre a mudança de sistema

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#681]
A partir da finalização das issues #682 #680:

- Anunciar o uso do Stripe para o pagamento da associação https://apyb.python.org.br/associados/associe-se/

- Avisar que evitar de usar o site antigo para renovar-se/associar-se

- Opções de pagamento via cartão, débito e boleto

- Pagamento via moeda estrangeira

**Comment by tiidadavena** [comment]
Redação do texto enviado para análise para as outras Diretoras.

**Comment by tiidadavena** [comment]
Arte aguardando revisão das diretoras

**Comment by tiidadavena** [comment]
Postagem prevista para amanhã
