### ISSUE TITLE
Atualizar ultradox - Reembolso

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#693]
Pontos para atualização:
- [ ] Inserir opção de pagamento via PIX (não é para excluir o pagamento por dados bancários completos, mas inserir uma outra opção de pagamento via PIX, assim como tem no formulário de Solicitação de pagamento)
- [ ] Trocar título do campo "Email do Responsável pelo Evento " por "Email do evento"
- [ ] Corrigir valor que apresenta na descrição do item no recibo gerado (na imagem abaixo o valor total está correto, mas o da descrição do item não está)
![image](https://github.com/apyb/tarefas/assets/30605862/a602f3cf-cbd1-4b3e-9935-0ae4698dbc09)

**Comment by naanadr** [comment]
@cecivieira estou tentando replicar esse erro de formatação do valor do item, mas para mim está sempre sendo formatado corretamente 🤔

**Comment by naanadr** [comment]
Mudanças realizadas:
* ![image](https://github.com/user-attachments/assets/09d8eebb-ebfc-424b-90d6-eb11985e2882)
* Achei que valia adicionar o e-mail da pessoa que vai receber o reembolso também: ![image](https://github.com/user-attachments/assets/1e5e7861-8bb6-4535-9011-e27adedb3b94)
* Não consegui fazer um checkbox que nem tinha no outro formulário, por isso acabei colocand
