### ISSUE TITLE
Ajuste fluxo ultradox - Solicitação de nota fiscal

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#695]
Ajustes solicitados:
- [ ] Substituir h1 "Solicitação de pagamento" por "Solicitação de nota fiscal" (imagem 1)
- [ ] Trocar título "Email do responsável do evento" por "Email do evento"

![image](https://github.com/apyb/tarefas/assets/30605862/10760694-a19a-4c57-ad88-b46f90274ee8)

**Comment by naanadr** [comment]
Mudanças realizadas
![image](https://github.com/user-attachments/assets/57dd94a3-98cb-457a-863b-0f564626e16d)
