### ISSUE TITLE
Ajuste fluxo ultradox - Gerador invoice

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#697]
Ajustes solicitados:
- [ ] Trocar título do campo "Email do Responsável pelo Evento" por "Email do evento"

**Comment by rougeth** [comment]
O que as pessoas organizando eventos menores que não tem email próprio devem preencher?

Um pouco de contexto sobre esse campo:

Ter o e-mail individual se provou útil quando a APyB estava servindo de infraestrutura para diversos eventos simultâneos (não lembro ao certo a quantidade, mas se não me falha a memória, chegamos a +10 em 2017 ou 18). A APyB tende a se envolver mais como os eventos maiores como Python Brasil ou Python Nordeste, mas foi difícil anteriormente para a diretoria ir atrás dos responsáveis para sanar dúvidas em relação aos formulários.

**Comment by cecivieira** [comment]
@rougeth para que a APyB forneça apoio ao evento, coletados os dados pessoas da big kahuna. Desse jeito, é possível entrar em contato com 1 pessoa, caso necessário.

Consideramos que usar o e-mail do evento para notificar sobre o fluxo do dinehiro, mais pessoas ficam cientes desse fluxo e  supervisionar.

**Comment by naanadr** [comment]
Campo alterado 
![image](https://github.com/user-attachments/assets/0be7df87-4558-4424-b59b-b1393ad5bbb5)
