### ISSUE TITLE
Corrigir fluxo Ultradox - Solicitação de pagamento

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#707]
O e-mail de notificação das novas solicitações de pagamento estão vindo sem o link para o comprovante fiscal.

Como está:
![image](https://github.com/user-attachments/assets/85470d93-cf32-4112-92a4-01023535406f)

Como deveria ser:
![image](https://github.com/user-attachments/assets/7c6293c2-4d59-4a59-ab9a-89f11e77a6b3)

**Comment by naanadr** [comment]
@cecivieira o fluxo não está quebrado, o link não foi enviado, porque o arquivo não foi salvo no drive:

![image](https://github.com/user-attachments/assets/c16131f7-d42a-4944-b9bd-e7274ea6f08b)

Talvez o arquivo não tenha sido salvo no driver, porque no campo `Descrição curta` acabaram escrevendo um paragrafo 🥲  Vou ver se tem como eu limitar a quantidade de caracteres que a pessoa escreve nesse campo.

![image](https://github.com/user-attachments/assets/c4f9325d-685e-4ff0-9adc-475a2e356df8)

**Comment by naanadr** [comment]
Delimitei para que esse campo seja preenchido com uma string de no máximo 20 caracteres:

![image](https://github.com/user-attachments/assets/ac6d9162-294e-49dc-98f3-b3dad118ee97)

![image](https://github.com/user-attachments/assets/882d2163-a149-4498-8547-4bc9b82e8bca)

**Comment by cecivieira** [comment]
O erro permanece
![image](https://github.com/user-attachments/assets/5c8bec6d-6065-4a36-8779-8bd37d85902e)

**Comment by naanadr** [comment]
@cecivieira esse erro pode ter persistido nessa thread de e-mail, porque ela é anterior a correção no formulário. Se aparecer esse problema novamente a partir de hoje, me avise.

**Comment by cecivieira** [comment]
Não rolou com o registro do pagamento recebido de uma invoice:
- O comprovante de recebimento não foi anexado na invoice
- A invoice não mudou para a pasta "receita". Ela permaneceu em "a receber"
![image](https://github.com/user-attachments/assets/62e87abe-4ef2-483d-8f60-07052c729c9e)

**Comment by cecivieira** [comment]
@naanadr identifiquei um padrão:

os comprovantes de reembolso estão sendo enviados no email

os comprovantes de pagamento NAO estão sendo enviados por email , consequentemente não estão sendo salvos na pasta DESPESAS

A PyNE acabou de abrir solicitação de pagamento. A nota fiscal veio.
Realizei o pagamento, usei o link para nexar o comprovante.
O e-mail de confirmação de pagamento foi enviado, mas sem o link do comporvante.

Fui napasta DESPESAS para verificar se o comprovante estava lá com a nota. NAo está

**Comment by naanadr** [comment]
@cecivieira acho que encontrei qual foi o problema, fiz a correção aqui! No entanto, a correção só começa a valer para solicitações novas, porque nos e-mails que já foram enviados os links anexados vão estar apontando para o fluxo quebrado. Dessa forma, para essas thread que o comprovante não está sendo anexado automaticamente, você precisará fazer manualmente.

Caso o problema ocorra novamente, me avisa aqui por favor 😄
