### ISSUE TITLE
Prêmio Dorneles Trémea/Jean Ferri - edição 2024

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#739]
- [x] Formulário de coleta
- [x] Publicação nas redes sociais
- [ ] Confecção das placas
- [ ] Divulgação da cerimônia de entrega

**Comment by tiidadavena** [comment]
Formulário inicial divulgado para as demais diretoras

**Comment by naanadr** [comment]
Informações sobre o horário que o prêmio será apresentado: https://github.com/pythonbrasil/pybr2024-org/issues/108

cc @apyb/diretoria

**Comment by tiidadavena** [comment]
Chamada postada nas redes sociais.

**Comment by naanadr** [comment]
Horário do prêmio ficou definido para sábado (19/10) às 16:30h

**Comment by tiidadavena** [comment]
A entrega do prêmio será feita dia 19/10 das 16h20 às 17h [conforme grade atualizada do evento](https://talks.python.org.br/pythonbrasil-2024/schedule/#2024-10-19)
