### ISSUE TITLE
Assembleia Geral 2024

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#740]
- [x] Decidir com a Org. da PyBR 2024
- [x] Definir se será formato híbrido
- [x] Divulgar a Assembleia
- [x] Imprimir a ata das pessoas associadas
- [x] Definir estrutura da Assembleia

**Comment by naanadr** [comment]
Issue onde se está definindo horário para a assembleia da APyB: https://github.com/pythonbrasil/pybr2024-org/issues/110

**Comment by tiidadavena** [comment]
Tendo em vista que a PyBR deste ano será trilha única, a estrutura da Assembleia precisará ajustar-se ao tempo limitado e viabilização de espaço próprio.

**Comment by tiidadavena** [comment]
De acordo com a #812, a assembleia ocorrerá no dia 19 de outubro, das 14h às 15h30min.

**Comment by tiidadavena** [comment]
Criar material de divulgação.
