### ISSUE TITLE
ultradox consertar fluxo pagamento boleto

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#760]
Não está anexando o boleto e documento fiscal referente a solicitação de pagamento com a modalidade de pagamento "boleto"

<img width="549" alt="image" src="https://github.com/user-attachments/assets/35356859-74d4-415d-a186-5b4e11669b60">

**Comment by cecivieira** [comment]
Comportamento intermitente.
A solicitação logo em seguida usando o mesmo fluxo e mesma modalidade de pagamento, foi processada corretamento com o anexo.

**Comment by naanadr** [comment]
Eu tinha mudado a senha do e-mail do `noreply` e aparentemente precisava atualizar no ultradox também, vou avisar nas issues abertas para o pessoal mandar e-mail de novo.

**Comment by naanadr** [comment]
Eu tinha mudado a senha do e-mail do `noreply` e aparentmente precisava atualizar no ultradox também, vou avisar nas issues abertas para

**Comment by naanadr** [comment]
@cecivieira esse problema aconteceu novamente em alguma thread de e-mail? se sim, tu pode mandar aqui na issue, por favor?

**Comment by cecivieira** [comment]
@naanadr ainda não me deparei com erro semelhante em outra solicitação. Caso haja, reabro essa issue

**Comment by naanadr** [comment]
Ok, fico aguardando então @cecivieira ❤️
