### ISSUE TITLE
fluxo ultradox quebrado

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#766]
paramos de receber por e-mail as solicitações registradas no ultradox, não importando o fluxo.
Temo issues abertas, que não recebemos e-mail.

**Comment by naanadr** [comment]
Eu tinha mudado a senha do e-mail do noreply e aparentemente precisava atualizar no ultradox também, vou avisar nas issues abertas para o pessoal mandar e-mail de novo.
