### ISSUE TITLE
Recebimento de patrocínio para Python Brasil vindo do exterior 

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#77]
https://github.com/pythonbrasil/pybr2022-org/issues/161

**Comment by muriloviana** [comment]
Patrocínio da Stream recebido com sucesso!

Inclusive adicionei um novo tópico na Wiki da associação sobre o processo feito: https://github.com/apyb/wiki/wiki/Financeiro#remessa-recebida-do-exterior
