### ISSUE TITLE
Financeiro da Python Sul 2020

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#78]

**Comment by muriloviana** [comment]
Irei revisitar essas transações ainda nesta semana, porém antes precisarei ir no BB recuperar meu acesso, pois perdi ele durante essa busca anterior 🙃

**Comment by muriloviana** [comment]
Discussão relacionada: https://github.com/apyb/comunidade/discussions/25#discussioncomment-2775353

**Comment by muriloviana** [comment]
Após uma nova busca foram encontradas as seguintes transações:

**Magrathea Labs**
O valor recebido (R$2.910,00) não bate com o valor emitido na nota fiscal (R$3.000,00):
Transação para a APyB: [pysul2020-magrathea.pdf](https://github.com/apyb/tarefas/files/8910885/pysul2020-magrathea.pdf)
NFe: [2020-03-04 nfe 166 R$3000,00 pysul2020 patrocinio Magrathea.pdf](https://github.com/apyb/tarefas/files/8910930/2020-03-04.nfe.166.R.3000.00.pysul2020.patrocinio.Magrathea.pdf)

**Python Pro**
Tudo ok, valor recebido (R$1.000,00) bate com o valor emitido na nota fiscal (R$1.000,00):
Transação para a APyB: [pysul2020-python-pro.pdf](https://github.com/apyb/tarefas/files/8910887/pysul2020-python-pro.pdf)
NFe: [2020-02-17 nfe 164 R$1000,00 pysul2020 patrocinio pythonpro.pdf](https://github.com/apyb/tarefas/files/8910925/2020-02-17.nfe.164.R.1000.00.pysul2020.patrocinio.pythonpro.pdf)

**Globo**
O valor recebido (R$950,00) não bate com o valor emitido na nota fiscal (R$1.000,00):
Transação para a APyB: [pysul2020-globo.pdf](https://github.com/apyb/tarefas/files/8910886/pysul2020-globo.pdf)
NFe: [2020-02-12 nfe 163 R$1000,00 pysul2020 patrocinio Globo.pdf](https://github.com/apyb/tarefas/files/8910948/2020-02-12.nfe.163.R.1000.00.pysul2020.patrocinio.Globo.pdf)

**ICRO**
Um nota fiscal foi emitida no valor de R$300,00, porém nenhum recebimento foi encontrado.
NFe: [2020-02-17 nfe 165 R$300,00 pysul2020 patrocinio ICRO.pdf](https://github.com/apyb/tarefas/files/8910957/2020-02-17.nfe.165.R.300.00.pysul2020.patrocinio.ICRO.pdf)

**Eventbrite**
Tudo ok, valor de R$2.934,80 recebido.
<img width="1083" alt="apyb-eventbrite-python-sul-2020" src="https://user-images.githubusercontent.com/6524275/173867223-ec589298-0fc0-45d6-8dd5-f9d75632dfb4.png">

**Comment by muriloviana** [comment]
A diferença dos valores, devido a taxas, e o recebimento em espécie do ICRO foram esclarecidos na mesma discussão mencionada anteriormente: https://github.com/apyb/comunidade/discussions/25#discussioncomment-2957531

Logo, o saldo atual da Python Sul 2020 junto a APyB é de:
- R$ 2.910,00 (Magrathea Labs)
- R$ 1.000,00 (Python Pro)
- R$ 950,00 (Globo)
- R$ 2.934,80 (Eventbrite)

Totalizando em: R$ 7.794,80 (sete mil setecentos e noventa e quatro reais e oitenta centavos) 

Acredito que seja interessante criarmos uma diretriz para as futuras organizações de eventos adicionarem nos contratos de patrocínio, que taxas e impostos referentes ao pagamentos do mesmo devem ser de responsabilidade das empresas patrocinadoras.
