### ISSUE TITLE
Montar template de email - Assembleia Geral 2022

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#81]
#### Pendências
[ ] - definir o local da Assembleia
[ ] - validar o corpo de email de convocatória
[ ] - divulgar o anúncio nas redes (Discussions, Twitter, Google Grupos)

#### Conteúdo

https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/SJDG7SBF5/edit

**Comment by rougeth** [comment]
- [ ] Documentar template na wiki

**Comment by tiidadavena** [comment]
Publicar anúncio no site da APyB a exemplo do que foi realizado no ano passado: https://python.org.br/assembleia2021/

Texto atualizado no Hackmd.

**Comment by tiidadavena** [comment]
Enviar esse texto para o associados@python.org.br e enviar também individualmente para as pessoas associadas.

**Comment by rougeth** [comment]
E-mails enviados.
