### ISSUE TITLE
Solicitação de Reembolso: Erro na plataforma

### ISSUE THREAD

**Issue by itepifanio** [apyb/tarefas#810]
#### Solicitação de Pagamento
- Evento: PyNE

Plataforma de solicitação de reembolso (https://www.ultradox.com/app/apyb-solicitacao-reembolso) com loading infinito ao carregar. Esse erro começou após a solicitação de um reembolso, não recebi email de confirmação desse reembolso e a tela de carregamento fica congelada desde então.

Já testei outras máquinas e navegadores, mas o problema parece persistir.

![image](https://github.com/user-attachments/assets/01a5ffc7-47f3-46c5-8693-faf5b9ce40c6)

**Comment by naanadr** [comment]
Obrigada @itepifanio por informar sobre o problema. Estava vendo os logs aqui do Ultradox e parece que consumimos todos os créditos do mês:

![image](https://github.com/user-attachments/assets/8c70e867-0e48-4c68-8699-cd37fd3ef2db)

**Comment by naanadr** [comment]
@itepifanio coloquei mais crédito na conta que deve ser o suficiente até o mês virar. Se você puder deixar para solicitar o resto dos reembolsos mês que vem, acho que é melhor 😄 menos chances dos créditos acabarem 🤣
