### ISSUE TITLE
Infraestrutura da assembleia online

### ISSUE THREAD

**Issue by naanadr** [apyb/tarefas#812]
Levantar informações sobre o local em que a assembleia irá acontecer, se possuí infraestrutura para suportar uma assembleia hibrida e também levantar como funcionará a dinâmica da assembleia.

**Comment by naanadr** [comment]
Conversas com a org da PyBR2024 estão acontecendo na issue https://github.com/pythonbrasil/pybr2024-org/issues/110

**Comment by naanadr** [comment]
@apyb/diretoria estava pesquisando ferramentas que poderiam ser utilizadas durante a assembleia para se comunicar com as pessoas que estarão remotamente participando. 

Olhando as funcionalidades do Google Meet que temos direito na nossa conta `Google Workspace para organizações sem fins lucrativos` (mais detalhes [aqui](https://www.google.com/intl/pt-BR/nonprofits/workspace/compare/)), essa ferramenta parece ser suficiente para que consigamos realizar a assembleia.

Imagino que ela atende as nossas necessidades, porque:
- Conseguimos receber até 100 pessoas, que deve ser o suficiente para uma segunda edição de assembleia online;
- Temos recurso de levantar a mão, que ajuda a organizar a fala das pessoas que estarão remotamente e aproxima as pessoas da assembleia;
- Temos recurso de pergunta e respostas, então caso alguém que esteja remotamente queira fazer perguntas e não necessariamente abrir o microfone, também poderá utilizar essa ferramenta;
- Temos disponível para uso o recurso de enquete, o que possibilita que consigamos organizar votações com as participantes remotas;
- Conseguimos gerar um link do meet antes da assembleia, o que ajuda a divulgar com antecedência como será o acesso para as pessoas remotas;
- Podemos utilizar o Google Forms para automatizar o preenchimento da ata de participantes da reunião, assim temos com certeza as informações de quem participou online e presencialmente.

![image](https://github.com/user-attachments/assets/2f9faa09-2523-4453-b624-b8c9b1801a5e)

O único recurso que não teremos disponível é a gravação da video chamada, porque o nosso plano é o mais simples. Eu particularmente não vejo necessidade em gravar a assembleia, caso vocês achem que seja necessário podemos utilizar o [OBS](https://obsproject.com/pt-br), porque o plano que permite gravar tela tem um custo elevado para a quantidade atual de usuários que possuímos:

![image](https://github.com/user-attachments/assets/18405181-65d5-4851-97f1-355755ca6db9)


O que vocês acham @apyb/diretoria ?

**Comment by tiidadavena** [comment]
De acordo!

Conforme mencionado na #839, será criada uma postagem sobre como preparar-se para a Assembleia.

**Comment by naanadr** [comment]
Estou aguardando a gente definir o dia e o horário para poder criar o link no google meet, e definir certinho toda a estrutura.

**Comment by naanadr** [comment]
Horário foi definido para o dia 19 de outubro, das 14h às 15h30min.

@tiidadavena link do meet:  `meet.google.com/duo-uxgh-mjf`. Mas para facilitar, você pode pedir para as pessoas salvarem o nosso calendário compartilhado (link [aqui](https://calendar.google.com/calendar/u/2?cid=Y19iMmZkMGQ0YzdlZTY1MDc5MTc0YWY5ZGVhMWYwM2E5NmU2ZmFjNGI3NGIzM2I4NTIxZWViOTI5ZDhlODdlYWE3QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20)).

**Comment by naanadr** [comment]
Todas as pessoas membras da assembleia, independente de estar no online ou não, irão assinar a ata de participação pelo link: `bit.ly/apyb-assembleia-2024` . Dessa forma, teremos a assinatura virtual de todas as pessoas participantes e o registro padronizado.

**Comment by tiidadavena** [comment]
> Como será o uso do meet durante a assembleia:
> 
>     * A sala ficará aberta para qualquer pessoa entrar durante a reunião;
>       
>       * Atualmente o status da sala está limitado.
> 
>     * Uma mensagem com os informes será pinada no chat, para que todas as pessoas que entrarem na reunião consigam ver a mensagem no chat:
> 
> 
> ```
> [INFORMES]
> - A assembleia inicia às 14h (UTC-3) e encerra às 15h30m ;
> - Pautas da assembleia: github.com/apyb/comunidade/discussions/128 ;
> - Assine a ata de presença: bit.ly/apyb-assembleia-2024 ;
> - Caso você deseje falar, utilize o "Levantar a mão";
> - Caso você tenha alguma dúvida, utilize o "Perguntas e Respostas" no canto inferior esquerdo;
> - Sempre que não for a sua vez de falar, mantenha o seu microfone fechado; 
> - Caso você deseje, pode deixar a câmera ligada;
> - A assembleia não está sendo gravada.
> ```

Incluir nos informes:

- Itens para discussão na assembleia
  - Apresentação, sabatina e votação das cidades candidatas para sediar a Python Brasil 2026
  - Apresentação da alteração do endereço fiscal da Associação e votação para inclusão no Estatuto
  - Demandas da comunidade apresentadas no [Github Discussions](https://github.com/apyb/comunidade/discussions/128)

- Seguir as normas de convivência saudável de acordo com o [Código de Conduta](https://apyb.python.org.br/pythonbrasil/cdc/)

**Comment by naanadr** [comment]
Informes ficará: 

```
[INFORMES]
- A assembleia inicia às 14h (UTC-3) e encerra às 15h30m ;
- Itens para discussão na assembleia:
  - Apresentação, sabatina e votação das cidades candidatas para sediar a Python Brasil 2026;
  - Apresentação da alteração do endereço fiscal da Associação e votação para inclusão no Estatuto;
  - Demandas da comunidade apresentadas no https://github.com/apyb/comunidade/discussions/128
- Assine a ata de presença: bit.ly/apyb-assembleia-2024 ;
- Caso você deseje falar, utilize o "Levantar a mão";
- Caso você tenha alguma dúvida, você também pode utilizar o "Perguntas e Respostas" no canto inferior esquerdo;
- Sempre que não for a sua vez de falar, mantenha o seu microfone fechado; 
- Caso você deseje, pode deixar a câmera ligada;
- A assembleia não está sendo gravada;
- Não esqueça de seguir as normas de convivência saudável de acordo com o Código de Conduta: https://apyb.python.org.br/pythonbrasil/cdc/
```

**Comment by cecivieira** [comment]
inclui nesses informes a votação para assembleia em espaço virtual
