### ISSUE TITLE
Ultradox - erro registro de comprovante de pagamento

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#817]
Ao tentar realizar o registro do comprovante de pagamento da solicitação https://www.ultradox.com/app/1KK6FhjUAHhjihs0YZcGO-KnbMIJeGVFS?rak=ag9zfmZsb3JleXNvZnR1ZHhyEgsSBVRpbWVyGICAiO-4_c8IDA , foi apresentada a tela de erro a seguir

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/5e5bce9f-837e-46a9-bc4c-2a89973e2e4f">

**Comment by naanadr** [comment]
Qual a thread de email que você pegou esse link @cecivieira ?

**Comment by cecivieira** [comment]
https://groups.google.com/g/apyb-condir/c/U3eluLldNYI/m/DZOVUNaDDQAJ

essa thread @naanadr

**Comment by naanadr** [comment]
@cecivieira esse erro parece ser no banco de dados do ultradox, eles parecem ter perdido a referência do link. Infelizmente não temos como corrigir isso 😞
