### ISSUE TITLE
Campanha: Candidatura cidade-sede PyBR 2024

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#82]
#### Candidatura cidade-sede 
[ ]  Montar o documento base com os textos para montar a thread nas redes de comunicação da APyB
[ ]  Validar o texto o documento 
[ ]  Disparar o texto nas redes
[ ] Documentar processo 
[ ] Atualizar a wiki da APyB (se aplicável)
[ ] Enviar dados atualizados para o texto do site da seção de candidatura

#### Verificar os materiais-base
- [Orientação mais atualizada no Manual do Big Kahuna](https://manual.pythonbrasil.org.br/proposta/index.html)
- [Manual do Big Kahuna](https://manual-do-big-kahuna.readthedocs.io/en/latest/proposta/modelo.html)
- [Template da candidatura de SC](https://docs.google.com/document/d/1g4YU1uIvHKrVSvL_3M6A8B8sSTZPPagpmnu9AMpr3Yg/edit)
- [Modelo de texto para chamada](https://blog.pythonbrasil.org.br/chamada-para-cidade-sede-da-python-brasil14.html)

#### Critérios para conclusão da atividade
[ ] - Texto validado e publicado

**Comment by tiidadavena** [comment]
Na reunião do dia 11/07/2022, #104 foi lançada a ideia de um Forms onde os resultados serão atualizados e publicados no Discussions para fomentar e debater as candidaturas. A ideia é que as candidaturas tenham um alto nível de qualidade.

**Comment by tiidadavena** [comment]
[Forms criado e atualizado](https://docs.google.com/forms/d/1-6KmlUUID1FRVfcmqJnENPoAgTnoLiixN9-YR9IzJ30/edit?usp=sharing).

Usei como base o [texto feito por Mário Sérgio](https://docs.google.com/document/d/1g4YU1uIvHKrVSvL_3M6A8B8sSTZPPagpmnu9AMpr3Yg/edit) pra a candidatura de Floripa + Manual do Big Kahuna.

**Comment by rougeth** [comment]
Eu acho que vale adicionar um item na lista de tarefas: Documentar processo e modelo de texto.

**Comment by rougeth** [comment]
Revisado @tiidadavena, único comentário é que, historicamente, a maioria das submissões são feitas durante o evento, as pessoas se empolgam e etc. Então, se a gente colocar muitas restrições/burocracia ("3 parágrafos (e com dados)" único ponto que fiquei + -) no form, acho que podemos acabar afastando as submissões.

Eu vejo o form mais como um guia para as pessoas se prepararem para a apresentação na assembleia.

**Comment by tiidadavena** [comment]
> Revisado @tiidadavena, único comentário é que, historicamente, a maioria das submissões são feitas durante o evento, as pessoas se empolgam e etc. Então, se a gente pedir algo mais completo (ex: "3 parágrafos") no form, acho que podemos acabar afastando as submissões.
> 
> Eu vejo o form mais como um guia para as pessoas se prepararem para a apresentação na assembleia.

Massa! Aproveitei e simplifiquei os textos de algumas perguntas e coloquei pra receber respostas mais curtas. Aijnda tô em dúvida sobre a parte de anexar um doc com a proposta.

**Comment by rougeth** [comment]
Além do formulário, é necessário enviar um PDF da proposta ou é opcional?

**Comment by tiidadavena** [comment]
> 

Tinha colocado como obrigatório, mas altererei para opcional :D

**Comment by tiidadavena** [comment]
Texto para publicação: https://hackmd.io/@u2yOy76-QDmjHbf3SjsJ1w/ByhF2_L-j

**Comment by tiidadavena** [comment]
Publicação realizada nas redes no dia 20/09.
