### ISSUE TITLE
Adicionar no fluxo de emissão de nota fiscal o pedido e armazenamento do recibo de pagamento

### ISSUE THREAD

**Issue by rougeth** [apyb/tarefas#84]
Adicionar no fluxo de emissão de nota fiscal o pedido e armazenamento do recibo de pagamento. Com essas informações, seria possível confirmar que o pagamento referente a nota fiscal foi de fato realizado.

**Comment by naanadr** [comment]
Atualização foi realizada, e mais contexto na issue #596
