### ISSUE TITLE
Help com numero de conta bancária

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#856]
Tenho os seguintes dados da apyb:

- Bank code: 001
- Branch code: 0089-2
- Account number: 78126-6

Mas o sistema da Elastic nos pede: ` To send a successful payment in BRL we need the account number, 3 digit bank number and the 4 digit branch code.`

Podemos entrar em contato com o gerente do banco e confirmar se podemos enviar para a agencia `0089`? Eles tentaram agencia `0892` e não rolou.

Ticket: https://pythonbrasil.freshdesk.com/a/tickets/11593

**Comment by cecivieira** [comment]
https://apyb.python.org.br/associados/guias/como-organizar-eventos/#quais-sao-os-dados-da-pessoa-juridica-da-apyb

todos os dados bancários estão no Guia

**Comment by biancarosa** [comment]
@cecivieira foram exatamente os dados que eu passei, e ainda assim deu erro no pagamento. 

como falei ali, o problema parece estar no número da agência. normalmente é um número de 4 dígitos.

podemos fazer o pagamento para a agência sem o dígito verificador?

**Comment by cecivieira** [comment]
@biancarosa a agência informada está com o dígito verificados.
Caso o pagamento seja possível via PIX, a chave é: 09344485000105 

<img width="165" alt="image" src="https://github.com/user-attachments/assets/b0572c96-e135-4bc5-a066-550342f37b93">

Se não resolver, podemos emitir um boleto no valor do pagamento.

**Comment by cecivieira** [comment]
A imagem do comentário anterior é um print do cabeçalho da nossa área do cliente no Banco do Brasil.

**Comment by biancarosa** [comment]
![image](https://github.com/user-attachments/assets/2badc9ed-8c6d-453e-bf95-18872db05a3e)

Tentei fazer uma transferência via Itaú. Não me deixou colocar o digito 2 na agência, mas reconheceu automaticamente o cnpj bonitinho com a agência 0089.

Pedi pra Elastic retentar sem digito.

**Comment by cecivieira** [comment]
Obrigada pela informação, Bia.
Essa é a primeira vez que temos erro desse tipo.
