### ISSUE TITLE
Solicitação dos últimos 3 relatórios enviados para a PSF

### ISSUE THREAD

**Issue by biancarosa** [apyb/tarefas#858]
Pessoal, a PSF pediu pra gente a quantidade de gente nos 3 últimos eventos e esses números tem várias fontes (eventbrite, repo de dados da pybr) e podem ser calculados de formas diferentes (incluindo ingressos cortesia ou não etc).

Não quero responder de forma que gere um diff entre a minha resposta e os reports. Vocês podem de dar acesso aos últimos 3 reports evnviados? Eu tenho da pybr2023 (que foi enviado pela gente) mas não da 2022 e 2021.

Abcs!

**Comment by naanadr** [comment]
Não encontrei os últimos reports da PSF na pasta do driver. Sobre o ano de 2022, talvez a @wasp-lahis e a @julianyraiol consigam ajudar. E sobre 2021, a @alynnefs pode ajudar nisso. 

@biancarosa se você não conseguir falar com elas, abre uma thread no [discussions](https://github.com/apyb/comunidade/discussions) que chega em mais pessoas.

**Comment by alynnefs** [comment]
Não lembro de ter feito report em 2021. Procurei o evento no Eventbrite e não aparece mais pra mim. Já tentou logar com o eventos@?

**Comment by biancarosa** [comment]
Conseguimos aqui galera! ❤️ ana dulce
