### ISSUE TITLE
Ultradox Receita - Quebrado

### ISSUE THREAD

**Issue by cecivieira** [apyb/tarefas#951]
Ao anexar o comprovante do recebimento de uma receita, é desparado o e-mail informando a organização do evento, mas o comprovante não está anexado (o link).

Esse foi o link que usei para anexar o comprovante da receita: https://www.ultradox.com/app/1IrErpi0H0QaGH7CkpbesHHF03XH4b1Pn?rak=ag9zfmZsb3JleXNvZnR1ZHhyEgsSBVRpbWVyGICAiPfunLIKDA

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/7af8c8b7-d6b3-4630-a878-12f31d922b37">

**Comment by naanadr** [comment]
@cecivieira acho que o ultradox está instável no geral, porque eu também não estou conseguindo abrir alguns links: 
![image](https://github.com/user-attachments/assets/e1043848-f23e-4357-a854-cd4e71be62bd)

**Comment by naanadr** [comment]
@cecivieira não consegui replicar o erro: 
![image](https://github.com/user-attachments/assets/330ff19b-1b98-4966-8195-3a01df794378)

Estou achando que foi um erro intermitente. 

Por sinal, os arquivos estão pendentes na pasta de `Receitas`
![image](https://github.com/user-attachments/assets/f05705a7-0829-4c9f-89a5-f46d1137b671)
