### ISSUE TITLE
Solicitação de documento para representação

### ISSUE THREAD

**Issue by MateusSantosMeuBem** [apyb/tarefas#972]
Oi, pessoal. Um dos patrocinadores da Python Norte 2024 pediu um documento que "demonstre meus poderes" frente à APyB em razão da Python Norte. A gente tem algo assim?

**Comment by naanadr** [comment]
@MateusSantosMeuBem próxima vez mande a dúvida no [Discussions](https://github.com/apyb/comunidade/discussions), porque ela pode ser a dúvida de outra pessoa no futuro.

A @anicelysantos está vendo isso e depois ela te retorna.

**Comment by anicelysantos** [comment]
@MateusSantosMeuBem qual seu email? vou compartilhar o documento para você preencher e em seguida eu assinar.

**Comment by anicelysantos** [comment]
@MateusSantosMeuBem qual seu email? vou compartilhar o documento para você preencher e em seguida eu assinar.

**Comment by MateusSantosMeuBem** [comment]
@anicelysantos, segue [o meu email](mailto:a.mateussm1.5@gmail.com).

**Comment by anicelysantos** [comment]
Feito!

**Comment by anicelysantos** [comment]
@MateusSantosMeuBem aqui está: https://drive.google.com/drive/u/0/folders/10ceEA5QDXRg8CKvpCavf24PljSKf7LBc

**Comment by MateusSantosMeuBem** [comment]
Brigadão, @anicelysantos!
