### ISSUE TITLE
Domínio Python Norte 2025

### ISSUE THREAD

**Issue by meu-bem** [apyb/tarefas#993]
Bom dia, @naanadr. Tudo bem?
Gostaria de solicitar o domínio para a Python Norte 2025.

Para APyB:

- [x] Configurar o subdomínio 2025. e apontar para pynorte.github.io
- [x] Configurar o domínio pythonnorte.org para redirecionar para o novo subdomínio

Para a org da Python Norte:
- [x] Configurar o domínio 2025.pythonnorte.org no repositório do site (https://github.com/PythonNorteBrasil/pynorte2025-site/settings/pages). Não esquecer de marcar a opção Enforce HTTPS.

**Comment by naanadr** [comment]
@meu-bem domínio configurado: 
![image](https://github.com/user-attachments/assets/c11bc69f-5518-4589-80b4-ae2da903409a)

**Comment by naanadr** [comment]
@meu-bem acho que está faltando você configurar o CNAME no repositório 🤔

**Comment by meu-bem** [comment]
@naanadr, eu não tenho ideia de como é feita essa configuração, mas podes "apontar" para https://pythonnortebrasil.github.io/pynorte2025-site/ ao invés de https://pythonnortebrasil.github.io/. Eu precisei adicionar esse `pynorte2025-site/` no arquivo do Vite pra funcionar no GitHub Pages.

**Comment by meu-bem** [comment]
![image](https://github.com/user-attachments/assets/afb10d43-8be4-4008-bfd1-a13c68fc10a7)

@naanadr, acredito quee do lado de cá, tá tudo certo.

**Comment by meu-bem** [comment]
oi, @naanadr. Tudo bem?
Tiveste algum retorno?

**Comment by naanadr** [comment]
@meu-bem desculpa a demora, tive uma semana difícil no trabalho.

estava olhando aqui, vocês mudaram de organização no github e o target do github deveria ser `pythonnortebrasil.github.io`.  
fiz a correção no CloudFlare e agora é só aguardar a propagação do DNS.

**Comment by naanadr** [comment]
@meu-bem DNS configurado, mas parece que o site está com problema para carregar os assets. Entendo que isso agora é do lado de vocês.

![image](https://github.com/user-attachments/assets/57a0257d-d4ac-4894-93bd-79d010853334)

**Comment by meu-bem** [comment]
Oi, @naanadr. Espero que estejas melhor e obrigado pelo retorno. Vou mexer no build essa noite pra solucionar esse problema.

**Comment by meu-bem** [comment]
Olá, @naanadr. Já consertei o código. Brigadão pela força!
