### ISSUE TITLE
Verificar assinatura do Autentique

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#997]
A Open Knowledge Brasil usa o [Autentique](https://www.autentique.com.br/) para assinatura do documento da ata da assembleia geral. 

Como é uma plataforma para geração de assinatura brasileira, está atuante de acordo com as leis e compliance do país.

O plano grátis permite assinar até 20 documentos

**Comment by tiidadavena** [comment]
conversei aqui com o bot do autentique e:
"Não, você não paga por cada assinatura em um mesmo documento no Autentique. Oferecemos dois planos: o Gratuito, que permite enviar até 20 documentos por mês para assinatura sem custo, e o Corporativo, que custa R$ 99,00 por mês ou R$ 999,00 por ano, com envio ilimitado de documentos. O pagamento é baseado no plano escolhido, não no número de assinaturas por documento."
Anicely Santos

**Comment by naanadr** [comment]
Conta criada e adicionada ao cofre
