### ISSUE TITLE
Documentar o passo-a-passo da Assembleia 

### ISSUE THREAD

**Issue by tiidadavena** [apyb/tarefas#999]
- [ ] Diagramas 
- [x] Datas e prazos
- [x] Documentação necessária
- [x] Emails das pessoas associadas

**Comment by naanadr** [comment]
Formulário para coleta dos e-mails das pessoas presentes na assembleia: https://forms.gle/5aJcPvyN8QofcFdg9

> O arquivo para edição está disponível [aqui](https://docs.google.com/forms/d/e/1FAIpQLSdTVGPIp6Pa7Y3vo8A6K4Eq26ZtzgFS5dMhBxW4vEt6XKg9xw/viewform?usp=sharing).

Ao final do formulário tem um [termo](https://docs.google.com/document/d/1xku_x-4lwPVPbr3EiT9q9zPztdewt_oVQ13JN55tNoU/pub) informando para que serve a coleta dos dados, caso deseje-se alterar o conteúdo do termo, acesse [essa página](https://docs.google.com/document/d/1xku_x-4lwPVPbr3EiT9q9zPztdewt_oVQ13JN55tNoU/edit?usp=sharing).

**Comment by naanadr** [comment]
[Rascunho](https://docs.google.com/document/d/1cBE_qienzkDNgW2v2SUeidxCXkG4b0xkB3sHK2n0OAw/edit?usp=sharing) da Ata da assembleia. [Rascunho](https://docs.google.com/document/d/1QINUhjCAWZ0AXAnfDYtlO2NIcnOwdM8jzNBGf-huOhg/edit?usp=sharing) do documento que deverá ser enviado para o cartório referente a mudança do estatuto.

> A ideia do **rascunho da ata da assembleia** é agilizar a escrita da ata, de forma que consigamos enviar a mesma para ser assinada pelos associados no mesmo dia da assembleia.
